%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'SOE_Decomposition';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('SOE_Decomposition.log');
M_.exo_names = 'eps_v';
M_.exo_names_tex = 'eps\_v';
M_.exo_names_long = 'eps_v';
M_.exo_names = char(M_.exo_names, 'eps_kappa');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_kappa');
M_.exo_names_long = char(M_.exo_names_long, 'eps_kappa');
M_.exo_names = char(M_.exo_names, 'eps_u');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_u');
M_.exo_names_long = char(M_.exo_names_long, 'eps_u');
M_.exo_names = char(M_.exo_names, 'eps_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_z');
M_.exo_names_long = char(M_.exo_names_long, 'eps_z');
M_.exo_names = char(M_.exo_names, 'eps_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a');
M_.exo_names = char(M_.exo_names, 'eps_zeta');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_zeta');
M_.exo_names_long = char(M_.exo_names_long, 'eps_zeta');
M_.exo_names = char(M_.exo_names, 'eps_yCo');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_yCo');
M_.exo_names_long = char(M_.exo_names_long, 'eps_yCo');
M_.exo_names = char(M_.exo_names, 'eps_Rstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Rstar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Rstar');
M_.exo_names = char(M_.exo_names, 'eps_pCostar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_pCostar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_pCostar');
M_.exo_names = char(M_.exo_names, 'eps_y_star');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_y\_star');
M_.exo_names_long = char(M_.exo_names_long, 'eps_y_star');
M_.exo_names = char(M_.exo_names, 'eps_g_c');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_c');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_c');
M_.exo_names = char(M_.exo_names, 'eps_g_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_i');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_i');
M_.exo_names = char(M_.exo_names, 'eps_TR');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_TR');
M_.exo_names_long = char(M_.exo_names_long, 'eps_TR');
M_.exo_names = char(M_.exo_names, 'eps_gam_YNCo_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_YNCo\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_YNCo_obs');
M_.exo_names = char(M_.exo_names, 'eps_gam_C_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_C\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_C_obs');
M_.exo_names = char(M_.exo_names, 'eps_gam_I_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_I\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_I_obs');
M_.exo_names = char(M_.exo_names, 'eps_xi_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_xi\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_xi_obs');
M_.exo_names = char(M_.exo_names, 'eps_pCostar_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_pCostar\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_pCostar_obs');
M_.exo_names = char(M_.exo_names, 'eps_YCo_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_YCo\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_YCo_obs');
M_.exo_names = char(M_.exo_names, 'eps_gam_G_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_G\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_G_obs');
M_.exo_names = char(M_.exo_names, 'eps_Rstar_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Rstar\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Rstar_obs');
M_.exo_names = char(M_.exo_names, 'eps_Ystar_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Ystar\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Ystar_obs');
M_.exo_names = char(M_.exo_names, 'eps_gam_Ig_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_Ig\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_Ig_obs');
M_.exo_names = char(M_.exo_names, 'eps_gam_TR_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gam\_TR\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gam_TR_obs');
M_.exo_names = char(M_.exo_names, 'eps_ratio_TBY_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ratio\_TBY\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ratio_TBY_obs');
M_.exo_names = char(M_.exo_names, 'eps_hours_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_hours\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_hours_obs');
M_.exo_names = char(M_.exo_names, 'eps_gama_YNCo_obs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_gama\_YNCo\_obs');
M_.exo_names_long = char(M_.exo_names_long, 'eps_gama_YNCo_obs');
M_.endo_names = 'lam_o';
M_.endo_names_tex = 'lam\_o';
M_.endo_names_long = 'lam_o';
M_.endo_names = char(M_.endo_names, 'c_hat_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_o');
M_.endo_names = char(M_.endo_names, 'c_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_o');
M_.endo_names = char(M_.endo_names, 'h_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_o');
M_.endo_names_long = char(M_.endo_names_long, 'h_o');
M_.endo_names = char(M_.endo_names, 'i_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_o');
M_.endo_names_long = char(M_.endo_names_long, 'i_o');
M_.endo_names = char(M_.endo_names, 'k_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_o');
M_.endo_names_long = char(M_.endo_names_long, 'k_o');
M_.endo_names = char(M_.endo_names, 'f_star_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star\_o');
M_.endo_names_long = char(M_.endo_names_long, 'f_star_o');
M_.endo_names = char(M_.endo_names, 'Theta_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_o');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_o');
M_.endo_names = char(M_.endo_names, 'chitil_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_o');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_o');
M_.endo_names = char(M_.endo_names, 'lam_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'lam\_r');
M_.endo_names_long = char(M_.endo_names_long, 'lam_r');
M_.endo_names = char(M_.endo_names, 'c_hat_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_r');
M_.endo_names = char(M_.endo_names, 'c_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_r');
M_.endo_names = char(M_.endo_names, 'h_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_r');
M_.endo_names_long = char(M_.endo_names_long, 'h_r');
M_.endo_names = char(M_.endo_names, 'Theta_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_r');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_r');
M_.endo_names = char(M_.endo_names, 'chitil_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_r');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_r');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'f_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star');
M_.endo_names_long = char(M_.endo_names_long, 'f_star');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'rK');
M_.endo_names_tex = char(M_.endo_names_tex, 'rK');
M_.endo_names_long = char(M_.endo_names_long, 'rK');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'yC');
M_.endo_names_tex = char(M_.endo_names_tex, 'yC');
M_.endo_names_long = char(M_.endo_names_long, 'yC');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'yH');
M_.endo_names_tex = char(M_.endo_names_tex, 'yH');
M_.endo_names_long = char(M_.endo_names_long, 'yH');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'xH');
M_.endo_names_tex = char(M_.endo_names_tex, 'xH');
M_.endo_names_long = char(M_.endo_names_long, 'xH');
M_.endo_names = char(M_.endo_names, 'xHstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'xHstar');
M_.endo_names_long = char(M_.endo_names_long, 'xHstar');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'pH');
M_.endo_names_tex = char(M_.endo_names_tex, 'pH');
M_.endo_names_long = char(M_.endo_names_long, 'pH');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'tb');
M_.endo_names_tex = char(M_.endo_names_tex, 'tb');
M_.endo_names_long = char(M_.endo_names_long, 'tb');
M_.endo_names = char(M_.endo_names, 'xi');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi');
M_.endo_names_long = char(M_.endo_names_long, 'xi');
M_.endo_names = char(M_.endo_names, 'tau_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_k');
M_.endo_names_long = char(M_.endo_names_long, 'tau_k');
M_.endo_names = char(M_.endo_names, 'tau_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_n');
M_.endo_names_long = char(M_.endo_names_long, 'tau_n');
M_.endo_names = char(M_.endo_names, 'tau_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_c');
M_.endo_names_long = char(M_.endo_names_long, 'tau_c');
M_.endo_names = char(M_.endo_names, 'k_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_g');
M_.endo_names_long = char(M_.endo_names_long, 'k_g');
M_.endo_names = char(M_.endo_names, 'g_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_c');
M_.endo_names_long = char(M_.endo_names_long, 'g_c');
M_.endo_names = char(M_.endo_names, 'g_i');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_i');
M_.endo_names_long = char(M_.endo_names_long, 'g_i');
M_.endo_names = char(M_.endo_names, 'tr');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr');
M_.endo_names_long = char(M_.endo_names_long, 'tr');
M_.endo_names = char(M_.endo_names, 'tr_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_o');
M_.endo_names_long = char(M_.endo_names_long, 'tr_o');
M_.endo_names = char(M_.endo_names, 'tr_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_r');
M_.endo_names_long = char(M_.endo_names_long, 'tr_r');
M_.endo_names = char(M_.endo_names, 'b_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_star');
M_.endo_names_long = char(M_.endo_names_long, 'b_star');
M_.endo_names = char(M_.endo_names, 'gdp_nco');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_nco');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_nco');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'kappa_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_o');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_o');
M_.endo_names = char(M_.endo_names, 'kappa_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_r');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_r');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'zeta');
M_.endo_names_tex = char(M_.endo_names_tex, 'zeta');
M_.endo_names_long = char(M_.endo_names_long, 'zeta');
M_.endo_names = char(M_.endo_names, 'yCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'yCo');
M_.endo_names_long = char(M_.endo_names_long, 'yCo');
M_.endo_names = char(M_.endo_names, 'pCostar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'y_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_star');
M_.endo_names = char(M_.endo_names, 'yNCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'yNCo');
M_.endo_names_long = char(M_.endo_names_long, 'yNCo');
M_.endo_names = char(M_.endo_names, 'gam_YNCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNCo');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNCo');
M_.endo_names = char(M_.endo_names, 'gama_YNCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'gama\_YNCo');
M_.endo_names_long = char(M_.endo_names_long, 'gama_YNCo');
M_.endo_names = char(M_.endo_names, 'gam_C');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C');
M_.endo_names = char(M_.endo_names, 'gam_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I');
M_.endo_names = char(M_.endo_names, 'gam_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_G');
M_.endo_names_long = char(M_.endo_names_long, 'gam_G');
M_.endo_names = char(M_.endo_names, 'gam_Ig');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Ig');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Ig');
M_.endo_names = char(M_.endo_names, 'ratio_BY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_BY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_BY');
M_.endo_names = char(M_.endo_names, 'ratio_TBY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_TBY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_TBY');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'gam_TR');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_TR');
M_.endo_names_long = char(M_.endo_names_long, 'gam_TR');
M_.endo_names = char(M_.endo_names, 'ratio_FY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_FY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_FY');
M_.endo_names = char(M_.endo_names, 'gam_YNCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNCo_obs');
M_.endo_names = char(M_.endo_names, 'gama_YNCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gama\_YNCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gama_YNCo_obs');
M_.endo_names = char(M_.endo_names, 'gam_C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C_obs');
M_.endo_names = char(M_.endo_names, 'gam_I_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I_obs');
M_.endo_names = char(M_.endo_names, 'xi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'xi_obs');
M_.endo_names = char(M_.endo_names, 'pCostar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar_obs');
M_.endo_names = char(M_.endo_names, 'YCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'YCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'YCo_obs');
M_.endo_names = char(M_.endo_names, 'gam_G_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_G\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_G_obs');
M_.endo_names = char(M_.endo_names, 'Rstar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar_obs');
M_.endo_names = char(M_.endo_names, 'Ystar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar_obs');
M_.endo_names = char(M_.endo_names, 'gam_Ig_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Ig\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Ig_obs');
M_.endo_names = char(M_.endo_names, 'gam_TR_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_TR\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_TR_obs');
M_.endo_names = char(M_.endo_names, 'ratio_TBY_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_TBY\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_TBY_obs');
M_.endo_names = char(M_.endo_names, 'hours_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hours\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hours_obs');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_3');
M_.endo_partitions = struct();
M_.param_names = 'varsigma';
M_.param_names_tex = 'varsigma';
M_.param_names_long = 'varsigma';
M_.param_names = char(M_.param_names, 'hpsi');
M_.param_names_tex = char(M_.param_names_tex, 'hpsi');
M_.param_names_long = char(M_.param_names_long, 'hpsi');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'o');
M_.param_names_tex = char(M_.param_names_tex, 'o');
M_.param_names_long = char(M_.param_names_long, 'o');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'upsilon');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon');
M_.param_names_long = char(M_.param_names_long, 'upsilon');
M_.param_names = char(M_.param_names, 'eta_c');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_c');
M_.param_names_long = char(M_.param_names_long, 'eta_c');
M_.param_names = char(M_.param_names, 'o_c');
M_.param_names_tex = char(M_.param_names_tex, 'o\_c');
M_.param_names_long = char(M_.param_names_long, 'o_c');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'eta_star');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_star');
M_.param_names_long = char(M_.param_names_long, 'eta_star');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'gamma_k');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_k');
M_.param_names_long = char(M_.param_names_long, 'gamma_k');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'xi_bar');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_bar');
M_.param_names_long = char(M_.param_names_long, 'xi_bar');
M_.param_names = char(M_.param_names, 'omega_G');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_G');
M_.param_names_long = char(M_.param_names_long, 'omega_G');
M_.param_names = char(M_.param_names, 'delta_g');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_g');
M_.param_names_long = char(M_.param_names_long, 'delta_g');
M_.param_names = char(M_.param_names, 'o_kg');
M_.param_names_tex = char(M_.param_names_tex, 'o\_kg');
M_.param_names_long = char(M_.param_names_long, 'o_kg');
M_.param_names = char(M_.param_names, 'o_star');
M_.param_names_tex = char(M_.param_names_tex, 'o\_star');
M_.param_names_long = char(M_.param_names_long, 'o_star');
M_.param_names = char(M_.param_names, 'tau_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_c_bar');
M_.param_names = char(M_.param_names, 'tau_n_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_n\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_n_bar');
M_.param_names = char(M_.param_names, 'tau_k_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_k\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_k_bar');
M_.param_names = char(M_.param_names, 'g_i_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_i\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_i_bar');
M_.param_names = char(M_.param_names, 'alpha_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_i');
M_.param_names = char(M_.param_names, 'gamma_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_i');
M_.param_names = char(M_.param_names, 'g_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_c_bar');
M_.param_names = char(M_.param_names, 'alpha_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_c');
M_.param_names = char(M_.param_names, 'gamma_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_c');
M_.param_names = char(M_.param_names, 'tr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tr\_bar');
M_.param_names_long = char(M_.param_names_long, 'tr_bar');
M_.param_names = char(M_.param_names, 'alpha_TR');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_TR');
M_.param_names_long = char(M_.param_names_long, 'alpha_TR');
M_.param_names = char(M_.param_names, 'gamma_TR');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_TR');
M_.param_names_long = char(M_.param_names_long, 'gamma_TR');
M_.param_names = char(M_.param_names, 'rho_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_g_i');
M_.param_names = char(M_.param_names, 'rho_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_g_c');
M_.param_names = char(M_.param_names, 'rho_TR');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_TR');
M_.param_names_long = char(M_.param_names_long, 'rho_TR');
M_.param_names = char(M_.param_names, 'sig_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'sig_g_i');
M_.param_names = char(M_.param_names, 'sig_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'sig_g_c');
M_.param_names = char(M_.param_names, 'sig_TR');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_TR');
M_.param_names_long = char(M_.param_names_long, 'sig_TR');
M_.param_names = char(M_.param_names, 'rho_v');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_v');
M_.param_names_long = char(M_.param_names_long, 'rho_v');
M_.param_names = char(M_.param_names, 'rho_kappa');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_kappa');
M_.param_names_long = char(M_.param_names_long, 'rho_kappa');
M_.param_names = char(M_.param_names, 'rho_u');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_u');
M_.param_names_long = char(M_.param_names_long, 'rho_u');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_zeta');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zeta');
M_.param_names_long = char(M_.param_names_long, 'rho_zeta');
M_.param_names = char(M_.param_names, 'rho_yCo');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_yCo');
M_.param_names_long = char(M_.param_names_long, 'rho_yCo');
M_.param_names = char(M_.param_names, 'rho_Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Rstar');
M_.param_names_long = char(M_.param_names_long, 'rho_Rstar');
M_.param_names = char(M_.param_names, 'rho_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'rho_pCostar');
M_.param_names = char(M_.param_names, 'rho_y_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_y\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_y_star');
M_.param_names = char(M_.param_names, 'sig_v');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_v');
M_.param_names_long = char(M_.param_names_long, 'sig_v');
M_.param_names = char(M_.param_names, 'sig_kappa');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_kappa');
M_.param_names_long = char(M_.param_names_long, 'sig_kappa');
M_.param_names = char(M_.param_names, 'sig_u');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_u');
M_.param_names_long = char(M_.param_names_long, 'sig_u');
M_.param_names = char(M_.param_names, 'sig_z');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_z');
M_.param_names_long = char(M_.param_names_long, 'sig_z');
M_.param_names = char(M_.param_names, 'sig_a');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_a');
M_.param_names_long = char(M_.param_names_long, 'sig_a');
M_.param_names = char(M_.param_names, 'sig_zeta');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_zeta');
M_.param_names_long = char(M_.param_names_long, 'sig_zeta');
M_.param_names = char(M_.param_names, 'sig_yCo');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_yCo');
M_.param_names_long = char(M_.param_names_long, 'sig_yCo');
M_.param_names = char(M_.param_names, 'sig_Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_Rstar');
M_.param_names_long = char(M_.param_names_long, 'sig_Rstar');
M_.param_names = char(M_.param_names, 'sig_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'sig_pCostar');
M_.param_names = char(M_.param_names, 'sig_y_star');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_y\_star');
M_.param_names_long = char(M_.param_names_long, 'sig_y_star');
M_.param_names = char(M_.param_names, 'v_ss');
M_.param_names_tex = char(M_.param_names_tex, 'v\_ss');
M_.param_names_long = char(M_.param_names_long, 'v_ss');
M_.param_names = char(M_.param_names, 'kappa_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_o_ss');
M_.param_names = char(M_.param_names, 'kappa_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_r_ss');
M_.param_names = char(M_.param_names, 'u_ss');
M_.param_names_tex = char(M_.param_names_tex, 'u\_ss');
M_.param_names_long = char(M_.param_names_long, 'u_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'zeta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_ss');
M_.param_names_long = char(M_.param_names_long, 'zeta_ss');
M_.param_names = char(M_.param_names, 'yCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'yCo_ss');
M_.param_names = char(M_.param_names, 'pCostar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pCostar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pCostar_ss');
M_.param_names = char(M_.param_names, 'Rstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rstar_ss');
M_.param_names = char(M_.param_names, 'y_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_star_ss');
M_.param_names = char(M_.param_names, 'sCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'sCo_ss');
M_.param_names = char(M_.param_names, 'sg_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sg\_ss');
M_.param_names_long = char(M_.param_names_long, 'sg_ss');
M_.param_names = char(M_.param_names, 'str_ss');
M_.param_names_tex = char(M_.param_names_tex, 'str\_ss');
M_.param_names_long = char(M_.param_names_long, 'str_ss');
M_.param_names = char(M_.param_names, 'T_ss');
M_.param_names_tex = char(M_.param_names_tex, 'T\_ss');
M_.param_names_long = char(M_.param_names_long, 'T_ss');
M_.param_names = char(M_.param_names, 'h_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_o_ss');
M_.param_names = char(M_.param_names, 'h_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_r_ss');
M_.param_names = char(M_.param_names, 'p_ss');
M_.param_names_tex = char(M_.param_names_tex, 'p\_ss');
M_.param_names_long = char(M_.param_names_long, 'p_ss');
M_.param_names = char(M_.param_names, 'i_r');
M_.param_names_tex = char(M_.param_names_tex, 'i\_r');
M_.param_names_long = char(M_.param_names_long, 'i_r');
M_.param_names = char(M_.param_names, 'k_r');
M_.param_names_tex = char(M_.param_names_tex, 'k\_r');
M_.param_names_long = char(M_.param_names_long, 'k_r');
M_.param_names = char(M_.param_names, 'b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'b\_bar');
M_.param_names_long = char(M_.param_names_long, 'b_bar');
M_.param_names = char(M_.param_names, 'sf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sf\_ss');
M_.param_names_long = char(M_.param_names_long, 'sf_ss');
M_.param_names = char(M_.param_names, 'fb_star_bar');
M_.param_names_tex = char(M_.param_names_tex, 'fb\_star\_bar');
M_.param_names_long = char(M_.param_names_long, 'fb_star_bar');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'b_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_star_ss');
M_.param_names = char(M_.param_names, 'f_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'f\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'f_star_ss');
M_.param_names = char(M_.param_names, 'tb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tb\_ss');
M_.param_names_long = char(M_.param_names_long, 'tb_ss');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 27;
M_.endo_nbr = 89;
M_.param_nbr = 88;
M_.orig_endo_nbr = 83;
M_.aux_vars(1).endo_index = 84;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 58;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 85;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 58;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(3).endo_index = 86;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 58;
M_.aux_vars(3).orig_lead_lag = -3;
M_.aux_vars(4).endo_index = 87;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 52;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 88;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 52;
M_.aux_vars(5).orig_lead_lag = -2;
M_.aux_vars(6).endo_index = 89;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 52;
M_.aux_vars(6).orig_lead_lag = -3;
options_.varobs = cell(1);
options_.varobs(1)  = {'gam_YNCo_obs'};
options_.varobs(2)  = {'gam_C_obs'};
options_.varobs(3)  = {'gam_I_obs'};
options_.varobs(4)  = {'xi_obs'};
options_.varobs(5)  = {'pCostar_obs'};
options_.varobs(6)  = {'YCo_obs'};
options_.varobs(7)  = {'Rstar_obs'};
options_.varobs(8)  = {'Ystar_obs'};
options_.varobs(9)  = {'gam_G_obs'};
options_.varobs(10)  = {'gam_Ig_obs'};
options_.varobs(11)  = {'gam_TR_obs'};
options_.varobs(12)  = {'ratio_TBY_obs'};
options_.varobs(13)  = {'hours_obs'};
options_.varobs_id = [ 70 72 73 74 75 76 78 79 77 80 81 82 83  ];
M_.Sigma_e = zeros(27, 27);
M_.Correlation_matrix = eye(27, 27);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('SOE_Decomposition_static');
erase_compiled_function('SOE_Decomposition_dynamic');
M_.orig_eq_nbr = 83;
M_.eq_nbr = 89;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 37 126;
 0 38 0;
 1 39 0;
 0 40 0;
 2 41 127;
 3 42 0;
 0 43 0;
 0 44 0;
 4 45 0;
 0 46 0;
 0 47 0;
 5 48 0;
 0 49 0;
 0 50 0;
 6 51 0;
 7 52 0;
 0 53 0;
 8 54 0;
 9 55 0;
 10 56 0;
 0 57 128;
 0 58 0;
 0 59 129;
 11 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 12 69 0;
 0 70 0;
 13 71 0;
 0 72 130;
 0 73 0;
 0 74 0;
 14 75 0;
 15 76 0;
 16 77 0;
 17 78 0;
 0 79 0;
 0 80 0;
 18 81 0;
 0 82 0;
 19 83 131;
 20 84 0;
 21 85 0;
 22 86 132;
 23 87 0;
 24 88 0;
 25 89 0;
 26 90 0;
 27 91 0;
 28 92 0;
 29 93 0;
 30 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 31 120 0;
 32 121 0;
 33 122 0;
 34 123 0;
 35 124 0;
 36 125 0;]';
M_.nstatic = 49;
M_.nfwrd   = 4;
M_.npred   = 33;
M_.nboth   = 3;
M_.nsfwrd   = 7;
M_.nspred   = 36;
M_.ndynamic   = 40;
M_.equations_tags = {
  1 , 'name' , 'Optimizer Marginal Utility of Consumption' ;
  2 , 'name' , 'Rule of Thumb Marginal Utility of Consumption' ;
  3 , 'name' , 'Aggregate Private Consumption' ;
  4 , 'name' , 'Optimizer Consumption/Leisure Condition' ;
  5 , 'name' , 'Rule of Thumb Comsumption/Leausre Condition' ;
  6 , 'name' , 'Aggregate Labor Supply' ;
  7 , 'name' , 'Optimizer Euler Equation' ;
  8 , 'name' , 'Final Good Production' ;
  9 , 'name' , 'Domestic Demand for Foreign Goods' ;
  10 , 'name' , 'Doemstic Demand for Home Goods' ;
  11 , 'name' , 'Foreign Demand for Home Goods' ;
  12 , 'name' , 'Home Good Production Function' ;
  13 , 'name' , 'Home Good Market Clearing' ;
  14 , 'name' , 'Final Good Market Clearing' ;
  15 , 'name' , 'GDP In Terms of Foreing Good' ;
  16 , 'name' , 'Trade Balance' ;
  17 , 'name' , 'Aggregate Privately Held Foreign Debt' ;
  18 , 'name' , 'Balance of Payments Identity' ;
  19 , 'name' , 'Country Premium' ;
  20 , 'name' , 'Evolution of Optimizer Capital' ;
  21 , 'name' , 'Aggregate Private Capital' ;
  22 , 'name' , 'Aggregate Private Investment' ;
  23 , 'name' , 'Tobins q for Private Investment' ;
  24 , 'name' , 'Return to Capital Equals Marginal Product of Capital' ;
  25 , 'name' , 'Wage Equals Marginal Product of Labor' ;
  26 , 'name' , 'Optimzer Investment First Order Condition' ;
  27 , 'name' , 'Import Market Clearing' ;
  28 , 'name' , 'Optimizer Consumption Composite' ;
  29 , 'name' , 'Rule of Thumb Consumption Composite' ;
  30 , 'name' , 'Optimizer Wealth Effect on Labor Supply 1' ;
  31 , 'name' , 'Optimizer Wealth Effect on Labor Supply 2' ;
  32 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 1' ;
  33 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 2' ;
  34 , 'name' , 'Government Budget Constraint' ;
  35 , 'name' , 'Transfers to Optimizers' ;
  36 , 'name' , 'Transfers to Rule of Thumb' ;
  37 , 'name' , 'Profits of Home Good Producer' ;
  38 , 'name' , 'Evolution of Government Capital' ;
  39 , 'name' , 'Consumption Tax' ;
  40 , 'name' , 'Labor Tax' ;
  41 , 'name' , 'Capital Tax' ;
  42 , 'name' , 'Government Investment Rule' ;
  43 , 'name' , 'Government Consumption Rule' ;
  44 , 'name' , 'Government Transfers Rule' ;
  45 , 'name' , 'Rule of Thumb Budget Constraint' ;
  46 , 'name' , 'Real Non-Oil GDP' ;
  47 , 'name' , 'Time Preference Shifter Process' ;
  48 , 'name' , 'Optimizer Labor Supply Preference Shifter Process' ;
  49 , 'name' , 'Rule of Thumb Labor Supply Preference Shifter Process' ;
  50 , 'name' , 'Investment Specific Productivity Process' ;
  51 , 'name' , 'TFP Process' ;
  52 , 'name' , 'Growth Rate Process' ;
  53 , 'name' , 'Oil Quantity Process' ;
  54 , 'name' , 'Idiosyncratic Component of Country Premium Process' ;
  55 , 'name' , 'Foreign Inerest Rate Process' ;
  56 , 'name' , 'Foreign GDP Process' ;
  57 , 'name' , 'Oil Price Process' ;
  58 , 'name' , 'Non-oil GDP' ;
  59 , 'name' , 'Growth Rate of Non-oil GDP' ;
  60 , 'name' , 'Annual Q/Q Growth Rate of Non-oil GDP' ;
  61 , 'name' , 'Growth Rate of Private Consumption' ;
  62 , 'name' , 'Growth Rate of Total Investment' ;
  63 , 'name' , 'Growth Rate of Government Consumption' ;
  64 , 'name' , 'Growth Rate of Government Investment' ;
  65 , 'name' , 'Change in Government Debt Over GDP' ;
  66 , 'name' , 'Change in foreign Debt Over GDP' ;
  67 , 'name' , 'Real Exchange Rate' ;
  68 , 'name' , 'Trade Balance Over GDP' ;
  69 , 'name' , 'Growt Rate of Government Transfers' ;
  70 , 'name' , 'Growth Rate of Non-oil GDP (Observation)' ;
  71 , 'name' , 'Annual Q/Q Growth Rate of Non-oil GDP (Observation)' ;
  72 , 'name' , 'Growth Rate of Private Consumption (Observation)' ;
  73 , 'name' , 'Growth Rate of Total Investment (Observation)' ;
  74 , 'name' , 'Country Premium (Observation)' ;
  75 , 'name' , 'Oil Price (Observation)' ;
  76 , 'name' , 'Oil Quantity (Observation)' ;
  77 , 'name' , 'Foreign Interest Rate (Observation)' ;
  78 , 'name' , 'Foreign GDP (Observation)' ;
  79 , 'name' , 'Growth Rate of Government Consumption (Observation)' ;
  80 , 'name' , 'Growth Rate of Government Investment (Observation)' ;
  81 , 'name' , 'Growth Rate of Transfers (Observation)' ;
  82 , 'name' , 'Trade Balance Over GDP (Observation)' ;
  83 , 'name' , 'Hours (Observation)' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:27];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(89, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(27, 1);
M_.params = NaN(88, 1);
M_.NNZDerivatives = [378; -1; -1];
close all;
M_.params( 3 ) = 1.00001;
sigma = M_.params( 3 );
M_.params( 6 ) = 0.015;
delta = M_.params( 6 );
M_.params( 8 ) = 0.27;
o = M_.params( 8 );
M_.params( 9 ) = 0.74;
chi = M_.params( 9 );
M_.params( 13 ) = .7;
omega = M_.params( 13 );
M_.params( 19 ) = 1;
omega_G = M_.params( 19 );
M_.params( 20 ) = 0.015;
delta_g = M_.params( 20 );
M_.params( 12 ) = .25;
o_c = M_.params( 12 );
M_.params( 21 ) = .1;
o_kg = M_.params( 21 );
M_.params( 15 ) = M_.params(21)*.34;
gamma = M_.params( 15 );
M_.params( 5 ) = 0.34-M_.params(15);
alpha = M_.params( 5 );
M_.params( 14 ) = 0.25;
eta_star = M_.params( 14 );
M_.params( 82 ) = .256;
sf_ss = M_.params( 82 );
M_.params( 73 ) = 0.106;
sg_ss = M_.params( 73 );
M_.params( 74 ) = .049;
str_ss = M_.params( 74 );
M_.params( 72 ) = 0.082;
sCo_ss = M_.params( 72 );
M_.params( 66 ) = 1.004962931573204;
a_ss = M_.params( 66 );
M_.params( 70 ) = 1.000978953692953;
Rstar_ss = M_.params( 70 );
M_.params( 18 ) = 1.012705786773885;
xi_bar = M_.params( 18 );
M_.params( 23 ) = .12;
tau_c_bar = M_.params( 23 );
M_.params( 25 ) = .25;
tau_k_bar = M_.params( 25 );
M_.params( 24 ) = .04;
tau_n_bar = M_.params( 24 );
M_.params( 81 ) = 1.42;
b_bar = M_.params( 81 );
M_.params( 79 ) = .16;
i_r = M_.params( 79 );
M_.params( 76 ) = 0.29543;
h_o_ss = M_.params( 76 );
M_.params( 77 ) = 0.29543;
h_r_ss = M_.params( 77 );
M_.params( 61 ) = 1;
v_ss = M_.params( 61 );
M_.params( 64 ) = 1;
u_ss = M_.params( 64 );
M_.params( 78 ) = 1;
p_ss = M_.params( 78 );
M_.params( 65 ) = 1;
z_ss = M_.params( 65 );
M_.params( 67 ) = 1;
zeta_ss = M_.params( 67 );
M_.params( 71 ) = 1;
y_star_ss = M_.params( 71 );
M_.params( 69 ) = 1;
pCostar_ss = M_.params( 69 );
M_.params( 47 ) = 0.645978544032117;
rho_yCo = M_.params( 47 );
M_.params( 48 ) = 0.7333263129578;
rho_Rstar = M_.params( 48 );
M_.params( 50 ) = 0.900547920881103;
rho_y_star = M_.params( 50 );
M_.params( 49 ) = 0.87142;
rho_pCostar = M_.params( 49 );
M_.params( 57 ) = 0.2068456510301851;
sig_yCo = M_.params( 57 );
M_.params( 58 ) = 0.002467793820158299;
sig_Rstar = M_.params( 58 );
M_.params( 60 ) = 0.004860470962342755;
sig_y_star = M_.params( 60 );
M_.params( 59 ) = 0.1918254414826146;
sig_pCostar = M_.params( 59 );
M_.params( 35 ) = 0.773151296679890;
rho_g_i = M_.params( 35 );
M_.params( 27 ) = 2.581136188194960;
alpha_g_i = M_.params( 27 );
M_.params( 28 ) = (-1.820671564944772);
gamma_g_i = M_.params( 28 );
M_.params( 38 ) = 0.168734928580098;
sig_g_i = M_.params( 38 );
M_.params( 36 ) = 0.881944929959026;
rho_g_c = M_.params( 36 );
M_.params( 30 ) = 0.593524641111012;
alpha_g_c = M_.params( 30 );
M_.params( 31 ) = (-0.497803637718900);
gamma_g_c = M_.params( 31 );
M_.params( 39 ) = 0.027681576551846;
sig_g_c = M_.params( 39 );
M_.params( 37 ) = 0.473017824489847;
rho_TR = M_.params( 37 );
M_.params( 33 ) = 5.462229514950716;
alpha_TR = M_.params( 33 );
M_.params( 34 ) = (-0.261494559041695);
gamma_TR = M_.params( 34 );
M_.params( 40 ) = 0.108155747321727;
sig_TR = M_.params( 40 );
M_.params( 4 ) = 3.421587887494021;
phi = M_.params( 4 );
M_.params( 1 ) = 0.738370963191099;
varsigma = M_.params( 1 );
M_.params( 2 ) = 2.210565902756527;
hpsi = M_.params( 2 );
M_.params( 7 ) = 6.075943008381720;
eta = M_.params( 7 );
M_.params( 16 ) = 8.854549591310821;
gamma_k = M_.params( 16 );
M_.params( 11 ) = 0.794029592118338;
eta_c = M_.params( 11 );
M_.params( 10 ) = 0.700769221922841;
upsilon = M_.params( 10 );
M_.params( 41 ) = 0.405751923331249;
rho_v = M_.params( 41 );
M_.params( 42 ) = 0.737600849685945;
rho_kappa = M_.params( 42 );
M_.params( 43 ) = 0.351761401463657;
rho_u = M_.params( 43 );
M_.params( 44 ) = 0.863272871391337;
rho_z = M_.params( 44 );
M_.params( 45 ) = 0.789357359547517;
rho_a = M_.params( 45 );
M_.params( 46 ) = 0.651794588641516;
rho_zeta = M_.params( 46 );
M_.params( 51 ) = 10.230704155806931;
sig_v = M_.params( 51 );
M_.params( 52 ) = 7.557924942236687;
sig_kappa = M_.params( 52 );
M_.params( 53 ) = 27.244717788035512;
sig_u = M_.params( 53 );
M_.params( 54 ) = 2.079262504182787;
sig_z = M_.params( 54 );
M_.params( 55 ) = 0.622816528299578;
sig_a = M_.params( 55 );
M_.params( 56 ) = 0.889746719504832;
sig_zeta = M_.params( 56 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(51)^2;
M_.Sigma_e(2, 2) = M_.params(52)^2;
M_.Sigma_e(3, 3) = M_.params(53)^2;
M_.Sigma_e(4, 4) = M_.params(54)^2;
M_.Sigma_e(5, 5) = M_.params(55)^2;
M_.Sigma_e(6, 6) = M_.params(56)^2;
M_.Sigma_e(7, 7) = M_.params(57)^2;
M_.Sigma_e(8, 8) = M_.params(58)^2;
M_.Sigma_e(9, 9) = M_.params(59)^2;
M_.Sigma_e(10, 10) = M_.params(60)^2;
M_.Sigma_e(11, 11) = M_.params(39)^2;
M_.Sigma_e(12, 12) = M_.params(38)^2;
M_.Sigma_e(13, 13) = M_.params(40)^2;
M_.Sigma_e(14, 14) = 2.77994e-05;
M_.Sigma_e(15, 15) = 3.68488e-05;
M_.Sigma_e(16, 16) = 0.0001211819;
M_.Sigma_e(17, 17) = 0;
M_.Sigma_e(18, 18) = 0;
M_.Sigma_e(19, 19) = 0;
M_.Sigma_e(20, 20) = 0;
M_.Sigma_e(21, 21) = 0;
M_.Sigma_e(22, 22) = 0;
M_.Sigma_e(23, 23) = 0;
M_.Sigma_e(24, 24) = 0;
M_.Sigma_e(25, 25) = 3.96066e-05;
M_.Sigma_e(26, 26) = 3.973210000000001e-05;
M_.Sigma_e(27, 27) = 0.0002371601;
M_.shock_groups.default.group1.label = 'Technology';
M_.shock_groups.default.group1.shocks = { 'eps_u' 'eps_z' 'eps_a'};
M_.shock_groups.default.group2.label = 'Foreign';
M_.shock_groups.default.group2.shocks = { 'eps_Rstar' 'eps_y_star'};
M_.shock_groups.default.group3.label = 'Oil';
M_.shock_groups.default.group3.shocks = { 'eps_pCostar' 'eps_yCo'};
M_.shock_groups.default.group4.label = 'Risk';
M_.shock_groups.default.group4.shocks = { 'eps_zeta'};
M_.shock_groups.default.group5.label = 'Preference';
M_.shock_groups.default.group5.shocks = { 'eps_v' 'eps_kappa'};
M_.shock_groups.default.group6.label = 'Fiscal';
M_.shock_groups.default.group6.shocks = { 'eps_g_c' 'eps_g_i' 'eps_TR'};
M_.shock_groups.default.group7.label = 'Measurement';
M_.shock_groups.default.group7.shocks = { 'eps_gam_YNCo_obs' 'eps_gam_C_obs' 'eps_gam_I_obs' 'eps_xi_obs' 'eps_pCostar_obs' 'eps_YCo_obs' 'eps_gam_G_obs' 'eps_Rstar_obs' 'eps_Ystar_obs' 'eps_gam_Ig_obs' 'eps_gam_TR_obs' 'eps_ratio_TBY_obs' 'eps_hours_obs' 'eps_gama_YNCo_obs'};
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, 0, Inf, 3, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, 0, 1, 3, 0.9, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, 0, Inf, 3, 0.5, 10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, 0, Inf, 3, 3, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, 0, Inf, 3, 6, 10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, 0, Inf, 3, 1.5, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, 0, 1, 3, 0.5, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 4, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.9, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, 0.700008, 0, 1, 3, 0.700008, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, NaN, (-Inf), Inf, 4, 0.027061, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 3, 0.133003, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, (-0.005595), (-Inf), 0, 3, (-0.005595), 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.475066, 0, 1, 3, 0.475066, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, NaN, (-Inf), Inf, 4, 0.152928, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, NaN, (-Inf), Inf, 3, 1.771814, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, (-0.128020), (-Inf), 0, 3, (-0.128020), 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, 0.371415, 0, 1, 3, 0.371415, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, NaN, (-Inf), Inf, 4, 0.097554, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 3, 3.519944, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, (-0.348167), (-Inf), 0, 3, (-0.348167), 2, NaN, NaN, NaN ];
set_dynare_seed('clock'); 
tmp1 = find(estim_params_.param_vals(:,1)==4);
estim_params_.param_vals(tmp1,2) = 0.1;
tmp1 = find(estim_params_.param_vals(:,1)==1);
estim_params_.param_vals(tmp1,2) = 0.9;
tmp1 = find(estim_params_.param_vals(:,1)==2);
estim_params_.param_vals(tmp1,2) = 0.5;
tmp1 = find(estim_params_.param_vals(:,1)==7);
estim_params_.param_vals(tmp1,2) = 3;
tmp1 = find(estim_params_.param_vals(:,1)==16);
estim_params_.param_vals(tmp1,2) = 6;
tmp1 = find(estim_params_.param_vals(:,1)==11);
estim_params_.param_vals(tmp1,2) = 1.5;
tmp1 = find(estim_params_.param_vals(:,1)==10);
estim_params_.param_vals(tmp1,2) = 0.5;
tmp1 = find(estim_params_.param_vals(:,1)==41);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==42);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==43);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==44);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==45);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==46);
estim_params_.param_vals(tmp1,2) = 0.75;
tmp1 = find(estim_params_.param_vals(:,1)==36);
estim_params_.param_vals(tmp1,2) = 0.700008;
tmp1 = find(estim_params_.param_vals(:,1)==30);
estim_params_.param_vals(tmp1,2) = 0.133003;
tmp1 = find(estim_params_.param_vals(:,1)==31);
estim_params_.param_vals(tmp1,2) = (-0.005595);
tmp1 = find(estim_params_.param_vals(:,1)==35);
estim_params_.param_vals(tmp1,2) = 0.475066;
tmp1 = find(estim_params_.param_vals(:,1)==27);
estim_params_.param_vals(tmp1,2) = 1.771814;
tmp1 = find(estim_params_.param_vals(:,1)==28);
estim_params_.param_vals(tmp1,2) = (-0.128020);
tmp1 = find(estim_params_.param_vals(:,1)==37);
estim_params_.param_vals(tmp1,2) = 0.371415;
tmp1 = find(estim_params_.param_vals(:,1)==33);
estim_params_.param_vals(tmp1,2) = 3.519944;
tmp1 = find(estim_params_.param_vals(:,1)==34);
estim_params_.param_vals(tmp1,2) = (-0.348167);
tmp1 = find(estim_params_.var_exo(:,1)==1);
estim_params_.var_exo(tmp1,2) = 1;
tmp1 = find(estim_params_.var_exo(:,1)==2);
estim_params_.var_exo(tmp1,2) = 4;
tmp1 = find(estim_params_.var_exo(:,1)==3);
estim_params_.var_exo(tmp1,2) = 1;
tmp1 = find(estim_params_.var_exo(:,1)==4);
estim_params_.var_exo(tmp1,2) = 0.1;
tmp1 = find(estim_params_.var_exo(:,1)==5);
estim_params_.var_exo(tmp1,2) = 0.1;
tmp1 = find(estim_params_.var_exo(:,1)==6);
estim_params_.var_exo(tmp1,2) = 0.9;
tmp1 = find(estim_params_.var_exo(:,1)==11);
estim_params_.var_exo(tmp1,2) = 0.027061;
tmp1 = find(estim_params_.var_exo(:,1)==12);
estim_params_.var_exo(tmp1,2) = 0.152928;
tmp1 = find(estim_params_.var_exo(:,1)==13);
estim_params_.var_exo(tmp1,2) = 0.097554;
M_.hessian_eq_zero=0;
options_.Opt6Numb= 50000;
mymap = [1 0 0 ;0 1 0; 0 0 1;0 0 0; 1 1 0; .588 .294 0 ; 0 1 1;.96 .96 .96 ];
options_.no_graph.shock_decomposition = 1;
options_.plot_shock_decomp.colormap = mymap;
options_.datafile = '/mq/manuel_projects/SOEM_EC/data/estim_data.xlsx';
options_.parameter_set = 'calibration';
options_.plot_shock_decomp.use_shock_groups = 'default';
var_list_ = char('gam_YNCo_obs','gam_C_obs','gam_I_obs','hours_obs','xi_obs','pCostar_obs','YCo_obs','gam_G_obs','Rstar_obs','Ystar_obs','gam_Ig_obs','gam_TR_obs','ratio_TBY_obs','gama_YNCo_obs');
[oo_,M_]= shock_decomposition(M_,oo_,options_,var_list_,bayestopt_,estim_params_);
options_.irf = 81;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('SOE_Decomposition_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('SOE_Decomposition_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('SOE_Decomposition_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('SOE_Decomposition_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('SOE_Decomposition_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('SOE_Decomposition_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('SOE_Decomposition_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
