%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'SOE_simulations';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('SOE_simulations.log');
M_.exo_names = 'eps_tau_c';
M_.exo_names_tex = 'eps\_tau\_c';
M_.exo_names_long = 'eps_tau_c';
M_.exo_names = char(M_.exo_names, 'eps_tau_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_tau\_n');
M_.exo_names_long = char(M_.exo_names_long, 'eps_tau_n');
M_.exo_names = char(M_.exo_names, 'eps_tau_k');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_tau\_k');
M_.exo_names_long = char(M_.exo_names_long, 'eps_tau_k');
M_.exo_names = char(M_.exo_names, 'eps_g_c');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_c');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_c');
M_.exo_names = char(M_.exo_names, 'eps_g_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_i');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_i');
M_.exo_names = char(M_.exo_names, 'eps_TR');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_TR');
M_.exo_names_long = char(M_.exo_names_long, 'eps_TR');
M_.endo_names = 'lam_o';
M_.endo_names_tex = 'lam\_o';
M_.endo_names_long = 'lam_o';
M_.endo_names = char(M_.endo_names, 'c_hat_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_o');
M_.endo_names = char(M_.endo_names, 'c_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_o');
M_.endo_names = char(M_.endo_names, 'h_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_o');
M_.endo_names_long = char(M_.endo_names_long, 'h_o');
M_.endo_names = char(M_.endo_names, 'i_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_o');
M_.endo_names_long = char(M_.endo_names_long, 'i_o');
M_.endo_names = char(M_.endo_names, 'k_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_o');
M_.endo_names_long = char(M_.endo_names_long, 'k_o');
M_.endo_names = char(M_.endo_names, 'f_star_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star\_o');
M_.endo_names_long = char(M_.endo_names_long, 'f_star_o');
M_.endo_names = char(M_.endo_names, 'Theta_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_o');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_o');
M_.endo_names = char(M_.endo_names, 'chitil_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_o');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_o');
M_.endo_names = char(M_.endo_names, 'lam_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'lam\_r');
M_.endo_names_long = char(M_.endo_names_long, 'lam_r');
M_.endo_names = char(M_.endo_names, 'c_hat_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_r');
M_.endo_names = char(M_.endo_names, 'c_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_r');
M_.endo_names = char(M_.endo_names, 'h_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_r');
M_.endo_names_long = char(M_.endo_names_long, 'h_r');
M_.endo_names = char(M_.endo_names, 'Theta_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_r');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_r');
M_.endo_names = char(M_.endo_names, 'chitil_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_r');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_r');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'f_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star');
M_.endo_names_long = char(M_.endo_names_long, 'f_star');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'rK');
M_.endo_names_tex = char(M_.endo_names_tex, 'rK');
M_.endo_names_long = char(M_.endo_names_long, 'rK');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'yC');
M_.endo_names_tex = char(M_.endo_names_tex, 'yC');
M_.endo_names_long = char(M_.endo_names_long, 'yC');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'yH');
M_.endo_names_tex = char(M_.endo_names_tex, 'yH');
M_.endo_names_long = char(M_.endo_names_long, 'yH');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'xH');
M_.endo_names_tex = char(M_.endo_names_tex, 'xH');
M_.endo_names_long = char(M_.endo_names_long, 'xH');
M_.endo_names = char(M_.endo_names, 'xHstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'xHstar');
M_.endo_names_long = char(M_.endo_names_long, 'xHstar');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'pH');
M_.endo_names_tex = char(M_.endo_names_tex, 'pH');
M_.endo_names_long = char(M_.endo_names_long, 'pH');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'tb');
M_.endo_names_tex = char(M_.endo_names_tex, 'tb');
M_.endo_names_long = char(M_.endo_names_long, 'tb');
M_.endo_names = char(M_.endo_names, 'xi');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi');
M_.endo_names_long = char(M_.endo_names_long, 'xi');
M_.endo_names = char(M_.endo_names, 'tau_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_k');
M_.endo_names_long = char(M_.endo_names_long, 'tau_k');
M_.endo_names = char(M_.endo_names, 'tau_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_n');
M_.endo_names_long = char(M_.endo_names_long, 'tau_n');
M_.endo_names = char(M_.endo_names, 'tau_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_c');
M_.endo_names_long = char(M_.endo_names_long, 'tau_c');
M_.endo_names = char(M_.endo_names, 'k_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_g');
M_.endo_names_long = char(M_.endo_names_long, 'k_g');
M_.endo_names = char(M_.endo_names, 'g_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_c');
M_.endo_names_long = char(M_.endo_names_long, 'g_c');
M_.endo_names = char(M_.endo_names, 'g_i');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_i');
M_.endo_names_long = char(M_.endo_names_long, 'g_i');
M_.endo_names = char(M_.endo_names, 'tr');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr');
M_.endo_names_long = char(M_.endo_names_long, 'tr');
M_.endo_names = char(M_.endo_names, 'tr_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_o');
M_.endo_names_long = char(M_.endo_names_long, 'tr_o');
M_.endo_names = char(M_.endo_names, 'tr_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_r');
M_.endo_names_long = char(M_.endo_names_long, 'tr_r');
M_.endo_names = char(M_.endo_names, 'b_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_star');
M_.endo_names_long = char(M_.endo_names_long, 'b_star');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names_long = char(M_.endo_names_long, 'gdp');
M_.endo_names = char(M_.endo_names, 'debt_agg_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'debt\_agg\_y');
M_.endo_names_long = char(M_.endo_names_long, 'debt_agg_y');
M_.endo_names = char(M_.endo_names, 'capital_agg');
M_.endo_names_tex = char(M_.endo_names_tex, 'capital\_agg');
M_.endo_names_long = char(M_.endo_names_long, 'capital_agg');
M_.endo_names = char(M_.endo_names, 'welfare_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'welfare\_o');
M_.endo_names_long = char(M_.endo_names_long, 'welfare_o');
M_.endo_names = char(M_.endo_names, 'welfare_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'welfare\_r');
M_.endo_names_long = char(M_.endo_names_long, 'welfare_r');
M_.endo_names = char(M_.endo_names, 'ce_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'ce\_o');
M_.endo_names_long = char(M_.endo_names_long, 'ce_o');
M_.endo_names = char(M_.endo_names, 'ce_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'ce\_r');
M_.endo_names_long = char(M_.endo_names_long, 'ce_r');
M_.endo_names = char(M_.endo_names, 't_revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_revenue');
M_.endo_names_long = char(M_.endo_names_long, 't_revenue');
M_.endo_names = char(M_.endo_names, 'o_revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 'o\_revenue');
M_.endo_names_long = char(M_.endo_names_long, 'o_revenue');
M_.endo_names = char(M_.endo_names, 'spending');
M_.endo_names_tex = char(M_.endo_names_tex, 'spending');
M_.endo_names_long = char(M_.endo_names_long, 'spending');
M_.endo_names = char(M_.endo_names, 'b_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_y');
M_.endo_names_long = char(M_.endo_names_long, 'b_y');
M_.endo_names = char(M_.endo_names, 'f_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_y');
M_.endo_names_long = char(M_.endo_names_long, 'f_y');
M_.endo_names = char(M_.endo_names, 'tR_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tR\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tR_y');
M_.endo_names = char(M_.endo_names, 'oR_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'oR\_y');
M_.endo_names_long = char(M_.endo_names_long, 'oR_y');
M_.endo_names = char(M_.endo_names, 'g_c_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_c\_y');
M_.endo_names_long = char(M_.endo_names_long, 'g_c_y');
M_.endo_names = char(M_.endo_names, 'g_i_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_i\_y');
M_.endo_names_long = char(M_.endo_names_long, 'g_i_y');
M_.endo_names = char(M_.endo_names, 'tr_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tr_y');
M_.endo_names = char(M_.endo_names, 'S_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_y');
M_.endo_names_long = char(M_.endo_names_long, 'S_y');
M_.endo_names = char(M_.endo_names, 'primary_balance_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'primary\_balance\_y');
M_.endo_names_long = char(M_.endo_names_long, 'primary_balance_y');
M_.endo_names = char(M_.endo_names, 'interest_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest\_y');
M_.endo_names_long = char(M_.endo_names_long, 'interest_y');
M_.endo_names = char(M_.endo_names, 'revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 'revenue');
M_.endo_names_long = char(M_.endo_names_long, 'revenue');
M_.endo_names = char(M_.endo_names, 'R_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_y');
M_.endo_names_long = char(M_.endo_names_long, 'R_y');
M_.endo_names = char(M_.endo_names, 'xi_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_a');
M_.endo_names_long = char(M_.endo_names_long, 'xi_a');
M_.endo_names = char(M_.endo_names, 'w_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_r');
M_.endo_names_long = char(M_.endo_names_long, 'w_r');
M_.endo_names = char(M_.endo_names, 'gdp_nco');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_nco');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_nco');
M_.endo_names = char(M_.endo_names, 'tau_c_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_c\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_c_y');
M_.endo_names = char(M_.endo_names, 'tau_n_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_n\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_n_y');
M_.endo_names = char(M_.endo_names, 'tau_k_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_k\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_k_y');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'kappa_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_o');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_o');
M_.endo_names = char(M_.endo_names, 'kappa_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_r');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_r');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'zeta');
M_.endo_names_tex = char(M_.endo_names_tex, 'zeta');
M_.endo_names_long = char(M_.endo_names_long, 'zeta');
M_.endo_names = char(M_.endo_names, 'yCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'yCo');
M_.endo_names_long = char(M_.endo_names_long, 'yCo');
M_.endo_names = char(M_.endo_names, 'pCostar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'y_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_star');
M_.endo_names = char(M_.endo_names, 'yNCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'yNCo');
M_.endo_names_long = char(M_.endo_names_long, 'yNCo');
M_.endo_names = char(M_.endo_names, 'gam_YNCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNCo');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNCo');
M_.endo_names = char(M_.endo_names, 'gam_C');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C');
M_.endo_names = char(M_.endo_names, 'gam_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I');
M_.endo_names = char(M_.endo_names, 'gam_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_G');
M_.endo_names_long = char(M_.endo_names_long, 'gam_G');
M_.endo_names = char(M_.endo_names, 'gam_Ig');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Ig');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Ig');
M_.endo_names = char(M_.endo_names, 'ratio_BY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_BY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_BY');
M_.endo_names = char(M_.endo_names, 'ratio_TBY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_TBY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_TBY');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'gam_TR');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_TR');
M_.endo_names_long = char(M_.endo_names_long, 'gam_TR');
M_.endo_names = char(M_.endo_names, 'ratio_FY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_FY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_FY');
M_.endo_names = char(M_.endo_names, 'gam_YNCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNCo_obs');
M_.endo_names = char(M_.endo_names, 'gam_C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C_obs');
M_.endo_names = char(M_.endo_names, 'gam_I_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I_obs');
M_.endo_names = char(M_.endo_names, 'xi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'xi_obs');
M_.endo_names = char(M_.endo_names, 'pCostar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar_obs');
M_.endo_names = char(M_.endo_names, 'YCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'YCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'YCo_obs');
M_.endo_names = char(M_.endo_names, 'gam_G_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_G\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_G_obs');
M_.endo_names = char(M_.endo_names, 'ratio_BY_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_BY\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_BY_obs');
M_.endo_names = char(M_.endo_names, 'Rstar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar_obs');
M_.endo_names = char(M_.endo_names, 'Ystar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar_obs');
M_.endo_names = char(M_.endo_names, 'gam_Ig_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Ig\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Ig_obs');
M_.endo_names = char(M_.endo_names, 'gam_TR_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_TR\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_TR_obs');
M_.endo_names = char(M_.endo_names, 'ratio_TBY_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_TBY\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_TBY_obs');
M_.endo_names = char(M_.endo_names, 'ratio_FY_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_FY\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_FY_obs');
M_.endo_names = char(M_.endo_names, 'hours_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hours\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hours_obs');
M_.endo_partitions = struct();
M_.param_names = 'varsigma';
M_.param_names_tex = 'varsigma';
M_.param_names_long = 'varsigma';
M_.param_names = char(M_.param_names, 'hpsi');
M_.param_names_tex = char(M_.param_names_tex, 'hpsi');
M_.param_names_long = char(M_.param_names_long, 'hpsi');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'o');
M_.param_names_tex = char(M_.param_names_tex, 'o');
M_.param_names_long = char(M_.param_names_long, 'o');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'upsilon');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon');
M_.param_names_long = char(M_.param_names_long, 'upsilon');
M_.param_names = char(M_.param_names, 'eta_c');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_c');
M_.param_names_long = char(M_.param_names_long, 'eta_c');
M_.param_names = char(M_.param_names, 'o_c');
M_.param_names_tex = char(M_.param_names_tex, 'o\_c');
M_.param_names_long = char(M_.param_names_long, 'o_c');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'eta_star');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_star');
M_.param_names_long = char(M_.param_names_long, 'eta_star');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'gamma_k');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_k');
M_.param_names_long = char(M_.param_names_long, 'gamma_k');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'xi_bar');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_bar');
M_.param_names_long = char(M_.param_names_long, 'xi_bar');
M_.param_names = char(M_.param_names, 'omega_G');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_G');
M_.param_names_long = char(M_.param_names_long, 'omega_G');
M_.param_names = char(M_.param_names, 'delta_g');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_g');
M_.param_names_long = char(M_.param_names_long, 'delta_g');
M_.param_names = char(M_.param_names, 'o_kg');
M_.param_names_tex = char(M_.param_names_tex, 'o\_kg');
M_.param_names_long = char(M_.param_names_long, 'o_kg');
M_.param_names = char(M_.param_names, 'o_star');
M_.param_names_tex = char(M_.param_names_tex, 'o\_star');
M_.param_names_long = char(M_.param_names_long, 'o_star');
M_.param_names = char(M_.param_names, 'tau_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_c_bar');
M_.param_names = char(M_.param_names, 'tau_n_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_n\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_n_bar');
M_.param_names = char(M_.param_names, 'tau_k_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_k\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_k_bar');
M_.param_names = char(M_.param_names, 'g_i_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_i\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_i_bar');
M_.param_names = char(M_.param_names, 'alpha_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_i');
M_.param_names = char(M_.param_names, 'gamma_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_i');
M_.param_names = char(M_.param_names, 'g_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_c_bar');
M_.param_names = char(M_.param_names, 'alpha_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_c');
M_.param_names = char(M_.param_names, 'gamma_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_c');
M_.param_names = char(M_.param_names, 'tr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tr\_bar');
M_.param_names_long = char(M_.param_names_long, 'tr_bar');
M_.param_names = char(M_.param_names, 'alpha_TR');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_TR');
M_.param_names_long = char(M_.param_names_long, 'alpha_TR');
M_.param_names = char(M_.param_names, 'gamma_TR');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_TR');
M_.param_names_long = char(M_.param_names_long, 'gamma_TR');
M_.param_names = char(M_.param_names, 'rho_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_g_i');
M_.param_names = char(M_.param_names, 'rho_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_g_c');
M_.param_names = char(M_.param_names, 'rho_TR');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_TR');
M_.param_names_long = char(M_.param_names_long, 'rho_TR');
M_.param_names = char(M_.param_names, 'sig_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'sig_g_i');
M_.param_names = char(M_.param_names, 'sig_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'sig_g_c');
M_.param_names = char(M_.param_names, 'sig_TR');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_TR');
M_.param_names_long = char(M_.param_names_long, 'sig_TR');
M_.param_names = char(M_.param_names, 'rho_tau_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_tau\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_tau_c');
M_.param_names = char(M_.param_names, 'rho_tau_n');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_tau\_n');
M_.param_names_long = char(M_.param_names_long, 'rho_tau_n');
M_.param_names = char(M_.param_names, 'rho_tau_k');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_tau\_k');
M_.param_names_long = char(M_.param_names_long, 'rho_tau_k');
M_.param_names = char(M_.param_names, 'sig_tau_c');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_tau\_c');
M_.param_names_long = char(M_.param_names_long, 'sig_tau_c');
M_.param_names = char(M_.param_names, 'sig_tau_n');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_tau\_n');
M_.param_names_long = char(M_.param_names_long, 'sig_tau_n');
M_.param_names = char(M_.param_names, 'sig_tau_k');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_tau\_k');
M_.param_names_long = char(M_.param_names_long, 'sig_tau_k');
M_.param_names = char(M_.param_names, 'rho_v');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_v');
M_.param_names_long = char(M_.param_names_long, 'rho_v');
M_.param_names = char(M_.param_names, 'rho_kappa');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_kappa');
M_.param_names_long = char(M_.param_names_long, 'rho_kappa');
M_.param_names = char(M_.param_names, 'rho_u');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_u');
M_.param_names_long = char(M_.param_names_long, 'rho_u');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_zeta');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zeta');
M_.param_names_long = char(M_.param_names_long, 'rho_zeta');
M_.param_names = char(M_.param_names, 'rho_yCo');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_yCo');
M_.param_names_long = char(M_.param_names_long, 'rho_yCo');
M_.param_names = char(M_.param_names, 'rho_Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Rstar');
M_.param_names_long = char(M_.param_names_long, 'rho_Rstar');
M_.param_names = char(M_.param_names, 'rho_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'rho_pCostar');
M_.param_names = char(M_.param_names, 'rho_y_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_y\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_y_star');
M_.param_names = char(M_.param_names, 'v_ss');
M_.param_names_tex = char(M_.param_names_tex, 'v\_ss');
M_.param_names_long = char(M_.param_names_long, 'v_ss');
M_.param_names = char(M_.param_names, 'kappa_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_o_ss');
M_.param_names = char(M_.param_names, 'kappa_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_r_ss');
M_.param_names = char(M_.param_names, 'u_ss');
M_.param_names_tex = char(M_.param_names_tex, 'u\_ss');
M_.param_names_long = char(M_.param_names_long, 'u_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'zeta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_ss');
M_.param_names_long = char(M_.param_names_long, 'zeta_ss');
M_.param_names = char(M_.param_names, 'yCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'yCo_ss');
M_.param_names = char(M_.param_names, 'pCostar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pCostar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pCostar_ss');
M_.param_names = char(M_.param_names, 'Rstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rstar_ss');
M_.param_names = char(M_.param_names, 'y_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_star_ss');
M_.param_names = char(M_.param_names, 'sCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'sCo_ss');
M_.param_names = char(M_.param_names, 'sg_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sg\_ss');
M_.param_names_long = char(M_.param_names_long, 'sg_ss');
M_.param_names = char(M_.param_names, 'str_ss');
M_.param_names_tex = char(M_.param_names_tex, 'str\_ss');
M_.param_names_long = char(M_.param_names_long, 'str_ss');
M_.param_names = char(M_.param_names, 'T_ss');
M_.param_names_tex = char(M_.param_names_tex, 'T\_ss');
M_.param_names_long = char(M_.param_names_long, 'T_ss');
M_.param_names = char(M_.param_names, 'h_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_o_ss');
M_.param_names = char(M_.param_names, 'h_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_r_ss');
M_.param_names = char(M_.param_names, 'p_ss');
M_.param_names_tex = char(M_.param_names_tex, 'p\_ss');
M_.param_names_long = char(M_.param_names_long, 'p_ss');
M_.param_names = char(M_.param_names, 'i_r');
M_.param_names_tex = char(M_.param_names_tex, 'i\_r');
M_.param_names_long = char(M_.param_names_long, 'i_r');
M_.param_names = char(M_.param_names, 'k_r');
M_.param_names_tex = char(M_.param_names_tex, 'k\_r');
M_.param_names_long = char(M_.param_names_long, 'k_r');
M_.param_names = char(M_.param_names, 'b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'b\_bar');
M_.param_names_long = char(M_.param_names_long, 'b_bar');
M_.param_names = char(M_.param_names, 'sf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sf\_ss');
M_.param_names_long = char(M_.param_names_long, 'sf_ss');
M_.param_names = char(M_.param_names, 'fb_star_bar');
M_.param_names_tex = char(M_.param_names_tex, 'fb\_star\_bar');
M_.param_names_long = char(M_.param_names_long, 'fb_star_bar');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'b_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_star_ss');
M_.param_names = char(M_.param_names, 'f_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'f\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'f_star_ss');
M_.param_names = char(M_.param_names, 'tb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tb\_ss');
M_.param_names_long = char(M_.param_names_long, 'tb_ss');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_names = char(M_.param_names, 'welfare_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'welfare\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'welfare_o_ss');
M_.param_names = char(M_.param_names, 'welfare_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'welfare\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'welfare_r_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 6;
M_.endo_nbr = 110;
M_.param_nbr = 86;
M_.orig_endo_nbr = 110;
M_.aux_vars = [];
M_.Sigma_e = zeros(6, 6);
M_.Correlation_matrix = eye(6, 6);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('SOE_simulations_static');
erase_compiled_function('SOE_simulations_dynamic');
M_.orig_eq_nbr = 110;
M_.eq_nbr = 110;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 34 144;
 0 35 0;
 1 36 0;
 0 37 0;
 2 38 145;
 3 39 0;
 0 40 0;
 0 41 0;
 4 42 0;
 0 43 0;
 0 44 0;
 5 45 0;
 0 46 0;
 0 47 0;
 6 48 0;
 7 49 0;
 0 50 0;
 8 51 0;
 9 52 0;
 10 53 0;
 0 54 146;
 0 55 0;
 0 56 147;
 11 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 12 66 0;
 0 67 0;
 13 68 0;
 14 69 148;
 15 70 0;
 16 71 0;
 17 72 0;
 18 73 0;
 19 74 0;
 20 75 0;
 0 76 0;
 0 77 0;
 21 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 22 107 149;
 23 108 0;
 24 109 0;
 25 110 150;
 26 111 0;
 27 112 0;
 28 113 0;
 29 114 0;
 30 115 0;
 31 116 0;
 32 117 0;
 33 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;]';
M_.nstatic = 74;
M_.nfwrd   = 3;
M_.npred   = 29;
M_.nboth   = 4;
M_.nsfwrd   = 7;
M_.nspred   = 33;
M_.ndynamic   = 36;
M_.equations_tags = {
  1 , 'name' , 'Optimizer Marginal Utility of Consumption' ;
  2 , 'name' , 'Rule of Thumb Marginal Utility of Consumption' ;
  3 , 'name' , 'Aggregate Private Consumption' ;
  4 , 'name' , 'Optimizer Consumption/Leisure Condition' ;
  5 , 'name' , 'Rule of Thumb Comsumption/Leausre Condition' ;
  6 , 'name' , 'Aggregate Labor Supply' ;
  7 , 'name' , 'Optimizer Euler Equation' ;
  8 , 'name' , 'Final Good Production' ;
  9 , 'name' , 'Domestic Demand for Foreign Goods' ;
  10 , 'name' , 'Doemstic Demand for Home Goods' ;
  11 , 'name' , 'Foreign Demand for Home Goods' ;
  12 , 'name' , 'Home Good Production Function' ;
  13 , 'name' , 'Home Good Market Clearing' ;
  14 , 'name' , 'Final Good Market Clearing' ;
  15 , 'name' , 'GDP In Terms of Foreing Good' ;
  16 , 'name' , 'Trade Balance' ;
  17 , 'name' , 'Aggregate Privately Held Foreign Debt' ;
  18 , 'name' , 'Balance of Payments Identity' ;
  19 , 'name' , 'Country Premium' ;
  20 , 'name' , 'Evolution of Optimizer Capital' ;
  21 , 'name' , 'Aggregate Private Capital' ;
  22 , 'name' , 'Aggregate Private Investment' ;
  23 , 'name' , 'Tobins q for Private Investment' ;
  24 , 'name' , 'Return to Capital Equals Marginal Product of Capital' ;
  25 , 'name' , 'Wage Equals Marginal Product of Labor' ;
  26 , 'name' , 'Optimzer Investment First Order Condition' ;
  27 , 'name' , 'Import Market Clearing' ;
  28 , 'name' , 'Optimizer Consumption Composite' ;
  29 , 'name' , 'Rule of Thumb Consumption Composite' ;
  30 , 'name' , 'Optimizer Wealth Effect on Labor Supply 1' ;
  31 , 'name' , 'Optimizer Wealth Effect on Labor Supply 2' ;
  32 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 1' ;
  33 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 2' ;
  34 , 'name' , 'Government Budget Constraint' ;
  35 , 'name' , 'Transfers to Optimizers' ;
  36 , 'name' , 'Transfers to Rule of Thumb' ;
  37 , 'name' , 'Profits of Home Good Producer' ;
  38 , 'name' , 'Evolution of Government Capital' ;
  39 , 'name' , 'Consumption Tax' ;
  40 , 'name' , 'Labor Tax' ;
  41 , 'name' , 'Capital Tax' ;
  42 , 'name' , 'Government Investment Rule' ;
  43 , 'name' , 'Government Consumption Rule' ;
  44 , 'name' , 'Government Transfers Rule' ;
  45 , 'name' , 'Rule of Thumb Budget Constraint' ;
  46 , 'name' , 'Real GDP' ;
  47 , 'name' , 'Annual Aggregate Debt to GDP' ;
  48 , 'name' , 'Aggregate Capitak' ;
  49 , 'name' , 'Optimizer Spot Utility' ;
  50 , 'name' , 'Rule of Thumb Spot Utiluty' ;
  51 , 'name' , 'Optimizer Consumption Equivalent Utility' ;
  52 , 'name' , 'Rule of Thumb Consumption Equivalent Utility' ;
  53 , 'name' , 'Tax Revenue' ;
  54 , 'name' , 'Oil Revenue' ;
  55 , 'name' , 'Revenue' ;
  56 , 'name' , 'Spending' ;
  57 , 'name' , 'Annual Government Debt to GDP' ;
  58 , 'name' , 'Annual Private Debt to GDP' ;
  59 , 'name' , 'Government Consumption to GDP' ;
  60 , 'name' , 'Government Investment to GDP' ;
  61 , 'name' , 'Transfers to GDP' ;
  62 , 'name' , 'Tax Revenue to GDP' ;
  63 , 'name' , 'Oil Revenue to GDP' ;
  64 , 'name' , 'Revenue to GDP' ;
  65 , 'name' , 'Spending to GDP' ;
  66 , 'name' , 'Primary Balance to GDP' ;
  67 , 'name' , 'Interest Payments to GDP' ;
  68 , 'name' , 'Annual Net Country Premium ' ;
  69 , 'name' , 'Real Wage' ;
  70 , 'name' , 'Real Non-Oil GDP' ;
  71 , 'name' , 'Consumption Tax Revenue to GDP' ;
  72 , 'name' , 'Labor Tax Revenue to GDP' ;
  73 , 'name' , 'Capital Tax Revenue to GDP' ;
  74 , 'name' , 'Time Preference Shifter Process' ;
  75 , 'name' , 'Optimizer Labor Supply Preference Shifter Process' ;
  76 , 'name' , 'Rule of Thumb Labor Supply Preference Shifter Process' ;
  77 , 'name' , 'Investment Specific Productivity Process' ;
  78 , 'name' , 'TFP Process' ;
  79 , 'name' , 'Growth Rate Process' ;
  80 , 'name' , 'Oil Quantity Process' ;
  81 , 'name' , 'Idiosyncratic Component of Country Premium Process' ;
  82 , 'name' , 'Foreign Inerest Rate Process' ;
  83 , 'name' , 'Foreign GDP Process' ;
  84 , 'name' , 'Oil Price Process' ;
  85 , 'name' , 'Non-oil GDP in Terms of Foreign Goods' ;
  86 , 'name' , 'Growth Rate of Non-oil GDP in Terms of Foreign goods' ;
  87 , 'name' , 'Growth Rate of Private Consumption in  terms of Foreign Goods' ;
  88 , 'name' , 'Growth Rate of Total Investment in Terms of Foreign Goods' ;
  89 , 'name' , 'Growth Rate of Government Consumption' ;
  90 , 'name' , 'Growth Rate of Government Investment' ;
  91 , 'name' , 'Change in Government Debt Over GDP' ;
  92 , 'name' , 'Change in foreign Debt Over GDP' ;
  93 , 'name' , 'Real Exchange Rate' ;
  94 , 'name' , 'Trade Balance Over GDP' ;
  95 , 'name' , 'Growt Rate of Government Transfers' ;
  96 , 'name' , 'Growth Rate of Non-oil GDP (Observation)' ;
  97 , 'name' , 'Growth Rate of Private Consumption (Observation)' ;
  98 , 'name' , 'Growth Rate of Total Investment (Observation)' ;
  99 , 'name' , 'Country Premium (Observation)' ;
  100 , 'name' , 'Oil Price (Observation)' ;
  101 , 'name' , 'Oil Quantity (Observation)' ;
  102 , 'name' , 'Foreign Interest Rate (Observation)' ;
  103 , 'name' , 'Foreign GDP (Observation)' ;
  104 , 'name' , 'Change in Government Debt Over GDP (Observation)' ;
  105 , 'name' , 'Change in Private Debt Pver GDP (Observation)' ;
  106 , 'name' , 'Growth Rate of Government Consumption (Observation)' ;
  107 , 'name' , 'Growth Rate of Government Investment (Observation)' ;
  108 , 'name' , 'Growth Rate of Transfers (Observation)' ;
  109 , 'name' , 'Trade Balance Over GDP (Observation)' ;
  110 , 'name' , 'Hours (Observation)' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:6];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(110, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(6, 1);
M_.params = NaN(86, 1);
M_.NNZDerivatives = [458; -1; -1];
close all;
M_.params( 3 ) = 1.000000001;
sigma = M_.params( 3 );
M_.params( 6 ) = 0.015;
delta = M_.params( 6 );
M_.params( 8 ) = 0.27;
o = M_.params( 8 );
M_.params( 9 ) = 0.74;
chi = M_.params( 9 );
M_.params( 13 ) = .7;
omega = M_.params( 13 );
M_.params( 19 ) = 1;
omega_G = M_.params( 19 );
M_.params( 20 ) = 0.015;
delta_g = M_.params( 20 );
M_.params( 12 ) = .25;
o_c = M_.params( 12 );
M_.params( 21 ) = .1;
o_kg = M_.params( 21 );
M_.params( 15 ) = M_.params(21)*.34;
gamma = M_.params( 15 );
M_.params( 5 ) = 0.34-M_.params(15);
alpha = M_.params( 5 );
M_.params( 14 ) = 0.25;
eta_star = M_.params( 14 );
M_.params( 78 ) = .256;
sf_ss = M_.params( 78 );
M_.params( 69 ) = 0.106;
sg_ss = M_.params( 69 );
M_.params( 70 ) = .049;
str_ss = M_.params( 70 );
M_.params( 68 ) = 0.082;
sCo_ss = M_.params( 68 );
M_.params( 62 ) = 1.004962931573204;
a_ss = M_.params( 62 );
M_.params( 66 ) = 1.000978953692953;
Rstar_ss = M_.params( 66 );
M_.params( 18 ) = 1.012705786773885;
xi_bar = M_.params( 18 );
M_.params( 23 ) = .12;
tau_c_bar = M_.params( 23 );
M_.params( 25 ) = .25;
tau_k_bar = M_.params( 25 );
M_.params( 24 ) = .04;
tau_n_bar = M_.params( 24 );
M_.params( 77 ) = 1.42;
b_bar = M_.params( 77 );
M_.params( 75 ) = .16;
i_r = M_.params( 75 );
M_.params( 72 ) = 0.29543;
h_o_ss = M_.params( 72 );
M_.params( 73 ) = 0.29543;
h_r_ss = M_.params( 73 );
M_.params( 57 ) = 1;
v_ss = M_.params( 57 );
M_.params( 60 ) = 1;
u_ss = M_.params( 60 );
M_.params( 74 ) = 1;
p_ss = M_.params( 74 );
M_.params( 61 ) = 1;
z_ss = M_.params( 61 );
M_.params( 63 ) = 1;
zeta_ss = M_.params( 63 );
M_.params( 67 ) = 1;
y_star_ss = M_.params( 67 );
M_.params( 65 ) = 1;
pCostar_ss = M_.params( 65 );
M_.params( 53 ) = 0.645978544032117;
rho_yCo = M_.params( 53 );
M_.params( 54 ) = 0.7333263129578;
rho_Rstar = M_.params( 54 );
M_.params( 56 ) = 0.900547920881103;
rho_y_star = M_.params( 56 );
M_.params( 55 ) = 0.87142;
rho_pCostar = M_.params( 55 );
M_.params( 41 ) = .999;
rho_tau_c = M_.params( 41 );
M_.params( 44 ) = .01;
sig_tau_c = M_.params( 44 );
M_.params( 42 ) = .999;
rho_tau_n = M_.params( 42 );
M_.params( 45 ) = .01;
sig_tau_n = M_.params( 45 );
M_.params( 43 ) = .999;
rho_tau_k = M_.params( 43 );
M_.params( 46 ) = .01;
sig_tau_k = M_.params( 46 );
M_.params( 35 ) = 0.773151296679890;
rho_g_i = M_.params( 35 );
M_.params( 27 ) = 2.581136188194960;
alpha_g_i = M_.params( 27 );
M_.params( 28 ) = (-1.820671564944772);
gamma_g_i = M_.params( 28 );
M_.params( 38 ) = 0.168734928580098;
sig_g_i = M_.params( 38 );
M_.params( 36 ) = 0.881944929959026;
rho_g_c = M_.params( 36 );
M_.params( 30 ) = 0.593524641111012;
alpha_g_c = M_.params( 30 );
M_.params( 31 ) = (-0.497803637718900);
gamma_g_c = M_.params( 31 );
M_.params( 39 ) = 0.027681576551846;
sig_g_c = M_.params( 39 );
M_.params( 37 ) = 0.473017824489847;
rho_TR = M_.params( 37 );
M_.params( 33 ) = 5.462229514950716;
alpha_TR = M_.params( 33 );
M_.params( 34 ) = (-0.261494559041695);
gamma_TR = M_.params( 34 );
M_.params( 40 ) = 0.108155747321727;
sig_TR = M_.params( 40 );
M_.params( 4 ) = 3.421587887494021;
phi = M_.params( 4 );
M_.params( 1 ) = 0.738370963191099;
varsigma = M_.params( 1 );
M_.params( 2 ) = 2.210565902756527;
hpsi = M_.params( 2 );
M_.params( 7 ) = 6.075943008381720;
eta = M_.params( 7 );
M_.params( 16 ) = 8.854549591310821;
gamma_k = M_.params( 16 );
M_.params( 11 ) = 0.794029592118338;
eta_c = M_.params( 11 );
M_.params( 10 ) = 0.700769221922841;
upsilon = M_.params( 10 );
M_.params( 47 ) = 0.405751923331249;
rho_v = M_.params( 47 );
M_.params( 48 ) = 0.737600849685945;
rho_kappa = M_.params( 48 );
M_.params( 49 ) = 0.351761401463657;
rho_u = M_.params( 49 );
M_.params( 50 ) = 0.863272871391337;
rho_z = M_.params( 50 );
M_.params( 51 ) = 0.789357359547517;
rho_a = M_.params( 51 );
M_.params( 52 ) = 0.651794588641516;
rho_zeta = M_.params( 52 );
sig_v        =	10.230704155806931;
sig_kappa    =	7.557924942236687;
sig_u	     =	27.244717788035512; 
sig_z        =	2.079262504182787; 
sig_a        =	0.622816528299578; 
sig_zeta     =	0.889746719504832; 
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(44)^2;
M_.Sigma_e(2, 2) = M_.params(45)^2;
M_.Sigma_e(3, 3) = M_.params(46)^2;
M_.Sigma_e(4, 4) = M_.params(39)^2;
M_.Sigma_e(5, 5) = M_.params(38)^2;
M_.Sigma_e(6, 6) = M_.params(40)^2;
options_.irf = 81;
options_.nograph = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('SOE_simulations_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('SOE_simulations_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('SOE_simulations_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('SOE_simulations_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('SOE_simulations_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('SOE_simulations_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('SOE_simulations_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
