%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'SOE_simulations_pf';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('SOE_simulations_pf.log');
M_.exo_names = 'eps_tau_c';
M_.exo_names_tex = 'eps\_tau\_c';
M_.exo_names_long = 'eps_tau_c';
M_.exo_names = char(M_.exo_names, 'eps_tau_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_tau\_n');
M_.exo_names_long = char(M_.exo_names_long, 'eps_tau_n');
M_.exo_names = char(M_.exo_names, 'eps_tau_k');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_tau\_k');
M_.exo_names_long = char(M_.exo_names_long, 'eps_tau_k');
M_.exo_names = char(M_.exo_names, 'eps_g_c');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_c');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_c');
M_.exo_names = char(M_.exo_names, 'eps_g_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g\_i');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g_i');
M_.exo_names = char(M_.exo_names, 'eps_tr');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_tr');
M_.exo_names_long = char(M_.exo_names_long, 'eps_tr');
M_.exo_names = char(M_.exo_names, 'eps_o_revenue');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_o\_revenue');
M_.exo_names_long = char(M_.exo_names_long, 'eps_o_revenue');
M_.exo_names = char(M_.exo_names, 'ind_imf');
M_.exo_names_tex = char(M_.exo_names_tex, 'ind\_imf');
M_.exo_names_long = char(M_.exo_names_long, 'ind_imf');
M_.endo_names = 'lam_o';
M_.endo_names_tex = 'lam\_o';
M_.endo_names_long = 'lam_o';
M_.endo_names = char(M_.endo_names, 'c_hat_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_o');
M_.endo_names = char(M_.endo_names, 'c_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_o');
M_.endo_names_long = char(M_.endo_names_long, 'c_o');
M_.endo_names = char(M_.endo_names, 'h_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_o');
M_.endo_names_long = char(M_.endo_names_long, 'h_o');
M_.endo_names = char(M_.endo_names, 'i_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_o');
M_.endo_names_long = char(M_.endo_names_long, 'i_o');
M_.endo_names = char(M_.endo_names, 'k_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_o');
M_.endo_names_long = char(M_.endo_names_long, 'k_o');
M_.endo_names = char(M_.endo_names, 'f_star_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star\_o');
M_.endo_names_long = char(M_.endo_names_long, 'f_star_o');
M_.endo_names = char(M_.endo_names, 'Theta_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_o');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_o');
M_.endo_names = char(M_.endo_names, 'chitil_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_o');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_o');
M_.endo_names = char(M_.endo_names, 'lam_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'lam\_r');
M_.endo_names_long = char(M_.endo_names_long, 'lam_r');
M_.endo_names = char(M_.endo_names, 'c_hat_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat_r');
M_.endo_names = char(M_.endo_names, 'c_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_r');
M_.endo_names = char(M_.endo_names, 'h_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_r');
M_.endo_names_long = char(M_.endo_names_long, 'h_r');
M_.endo_names = char(M_.endo_names, 'Theta_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'Theta\_r');
M_.endo_names_long = char(M_.endo_names_long, 'Theta_r');
M_.endo_names = char(M_.endo_names, 'chitil_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil\_r');
M_.endo_names_long = char(M_.endo_names_long, 'chitil_r');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'f_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_star');
M_.endo_names_long = char(M_.endo_names_long, 'f_star');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'rK');
M_.endo_names_tex = char(M_.endo_names_tex, 'rK');
M_.endo_names_long = char(M_.endo_names_long, 'rK');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'yC');
M_.endo_names_tex = char(M_.endo_names_tex, 'yC');
M_.endo_names_long = char(M_.endo_names_long, 'yC');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'yH');
M_.endo_names_tex = char(M_.endo_names_tex, 'yH');
M_.endo_names_long = char(M_.endo_names_long, 'yH');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'xH');
M_.endo_names_tex = char(M_.endo_names_tex, 'xH');
M_.endo_names_long = char(M_.endo_names_long, 'xH');
M_.endo_names = char(M_.endo_names, 'xHstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'xHstar');
M_.endo_names_long = char(M_.endo_names_long, 'xHstar');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'pH');
M_.endo_names_tex = char(M_.endo_names_tex, 'pH');
M_.endo_names_long = char(M_.endo_names_long, 'pH');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'tb');
M_.endo_names_tex = char(M_.endo_names_tex, 'tb');
M_.endo_names_long = char(M_.endo_names_long, 'tb');
M_.endo_names = char(M_.endo_names, 'xi');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi');
M_.endo_names_long = char(M_.endo_names_long, 'xi');
M_.endo_names = char(M_.endo_names, 'k_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_g');
M_.endo_names_long = char(M_.endo_names_long, 'k_g');
M_.endo_names = char(M_.endo_names, 'tr_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_o');
M_.endo_names_long = char(M_.endo_names_long, 'tr_o');
M_.endo_names = char(M_.endo_names, 'tr_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_r');
M_.endo_names_long = char(M_.endo_names_long, 'tr_r');
M_.endo_names = char(M_.endo_names, 'b_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_star');
M_.endo_names_long = char(M_.endo_names_long, 'b_star');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names_long = char(M_.endo_names_long, 'gdp');
M_.endo_names = char(M_.endo_names, 'debt_agg_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'debt\_agg\_y');
M_.endo_names_long = char(M_.endo_names_long, 'debt_agg_y');
M_.endo_names = char(M_.endo_names, 'capital_agg');
M_.endo_names_tex = char(M_.endo_names_tex, 'capital\_agg');
M_.endo_names_long = char(M_.endo_names_long, 'capital_agg');
M_.endo_names = char(M_.endo_names, 't_revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_revenue');
M_.endo_names_long = char(M_.endo_names_long, 't_revenue');
M_.endo_names = char(M_.endo_names, 'o_revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 'o\_revenue');
M_.endo_names_long = char(M_.endo_names_long, 'o_revenue');
M_.endo_names = char(M_.endo_names, 'spending');
M_.endo_names_tex = char(M_.endo_names_tex, 'spending');
M_.endo_names_long = char(M_.endo_names_long, 'spending');
M_.endo_names = char(M_.endo_names, 'b_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_y');
M_.endo_names_long = char(M_.endo_names_long, 'b_y');
M_.endo_names = char(M_.endo_names, 'f_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_y');
M_.endo_names_long = char(M_.endo_names_long, 'f_y');
M_.endo_names = char(M_.endo_names, 'tR_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tR\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tR_y');
M_.endo_names = char(M_.endo_names, 'oR_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'oR\_y');
M_.endo_names_long = char(M_.endo_names_long, 'oR_y');
M_.endo_names = char(M_.endo_names, 'g_c_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_c\_y');
M_.endo_names_long = char(M_.endo_names_long, 'g_c_y');
M_.endo_names = char(M_.endo_names, 'g_i_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_i\_y');
M_.endo_names_long = char(M_.endo_names_long, 'g_i_y');
M_.endo_names = char(M_.endo_names, 'tr_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tr_y');
M_.endo_names = char(M_.endo_names, 'S_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_y');
M_.endo_names_long = char(M_.endo_names_long, 'S_y');
M_.endo_names = char(M_.endo_names, 'primary_balance_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'primary\_balance\_y');
M_.endo_names_long = char(M_.endo_names_long, 'primary_balance_y');
M_.endo_names = char(M_.endo_names, 'interest_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest\_y');
M_.endo_names_long = char(M_.endo_names_long, 'interest_y');
M_.endo_names = char(M_.endo_names, 'revenue');
M_.endo_names_tex = char(M_.endo_names_tex, 'revenue');
M_.endo_names_long = char(M_.endo_names_long, 'revenue');
M_.endo_names = char(M_.endo_names, 'R_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_y');
M_.endo_names_long = char(M_.endo_names_long, 'R_y');
M_.endo_names = char(M_.endo_names, 'xi_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_a');
M_.endo_names_long = char(M_.endo_names_long, 'xi_a');
M_.endo_names = char(M_.endo_names, 'w_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_r');
M_.endo_names_long = char(M_.endo_names_long, 'w_r');
M_.endo_names = char(M_.endo_names, 'gdp_nco');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp\_nco');
M_.endo_names_long = char(M_.endo_names_long, 'gdp_nco');
M_.endo_names = char(M_.endo_names, 'tau_c_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_c\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_c_y');
M_.endo_names = char(M_.endo_names, 'tau_n_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_n\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_n_y');
M_.endo_names = char(M_.endo_names, 'tau_k_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_k\_y');
M_.endo_names_long = char(M_.endo_names_long, 'tau_k_y');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'tau_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_c');
M_.endo_names_long = char(M_.endo_names_long, 'tau_c');
M_.endo_names = char(M_.endo_names, 'tau_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_n');
M_.endo_names_long = char(M_.endo_names_long, 'tau_n');
M_.endo_names = char(M_.endo_names, 'tau_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_k');
M_.endo_names_long = char(M_.endo_names_long, 'tau_k');
M_.endo_names = char(M_.endo_names, 'g_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_c');
M_.endo_names_long = char(M_.endo_names_long, 'g_c');
M_.endo_names = char(M_.endo_names, 'g_i');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_i');
M_.endo_names_long = char(M_.endo_names_long, 'g_i');
M_.endo_names = char(M_.endo_names, 'tr');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr');
M_.endo_names_long = char(M_.endo_names_long, 'tr');
M_.endo_names = char(M_.endo_names, 'ratio_BY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_BY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_BY');
M_.endo_names = char(M_.endo_names, 'ratio_TBY');
M_.endo_names_tex = char(M_.endo_names_tex, 'ratio\_TBY');
M_.endo_names_long = char(M_.endo_names_long, 'ratio_TBY');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'kappa_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_o');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_o');
M_.endo_names = char(M_.endo_names, 'kappa_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa\_r');
M_.endo_names_long = char(M_.endo_names_long, 'kappa_r');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'zeta');
M_.endo_names_tex = char(M_.endo_names_tex, 'zeta');
M_.endo_names_long = char(M_.endo_names_long, 'zeta');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'y_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_star');
M_.endo_partitions = struct();
M_.param_names = 'varsigma';
M_.param_names_tex = 'varsigma';
M_.param_names_long = 'varsigma';
M_.param_names = char(M_.param_names, 'hpsi');
M_.param_names_tex = char(M_.param_names_tex, 'hpsi');
M_.param_names_long = char(M_.param_names_long, 'hpsi');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'o');
M_.param_names_tex = char(M_.param_names_tex, 'o');
M_.param_names_long = char(M_.param_names_long, 'o');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'upsilon');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon');
M_.param_names_long = char(M_.param_names_long, 'upsilon');
M_.param_names = char(M_.param_names, 'eta_c');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_c');
M_.param_names_long = char(M_.param_names_long, 'eta_c');
M_.param_names = char(M_.param_names, 'o_c');
M_.param_names_tex = char(M_.param_names_tex, 'o\_c');
M_.param_names_long = char(M_.param_names_long, 'o_c');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'eta_star');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_star');
M_.param_names_long = char(M_.param_names_long, 'eta_star');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'gamma_k');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_k');
M_.param_names_long = char(M_.param_names_long, 'gamma_k');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'xi_bar');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_bar');
M_.param_names_long = char(M_.param_names_long, 'xi_bar');
M_.param_names = char(M_.param_names, 'omega_G');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_G');
M_.param_names_long = char(M_.param_names_long, 'omega_G');
M_.param_names = char(M_.param_names, 'delta_g');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_g');
M_.param_names_long = char(M_.param_names_long, 'delta_g');
M_.param_names = char(M_.param_names, 'o_kg');
M_.param_names_tex = char(M_.param_names_tex, 'o\_kg');
M_.param_names_long = char(M_.param_names_long, 'o_kg');
M_.param_names = char(M_.param_names, 'o_star');
M_.param_names_tex = char(M_.param_names_tex, 'o\_star');
M_.param_names_long = char(M_.param_names_long, 'o_star');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'g_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_c_bar');
M_.param_names = char(M_.param_names, 'g_i_bar');
M_.param_names_tex = char(M_.param_names_tex, 'g\_i\_bar');
M_.param_names_long = char(M_.param_names_long, 'g_i_bar');
M_.param_names = char(M_.param_names, 'tr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tr\_bar');
M_.param_names_long = char(M_.param_names_long, 'tr_bar');
M_.param_names = char(M_.param_names, 'alpha_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_i');
M_.param_names = char(M_.param_names, 'gamma_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_i');
M_.param_names = char(M_.param_names, 'alpha_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'alpha_g_c');
M_.param_names = char(M_.param_names, 'gamma_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_g_c');
M_.param_names = char(M_.param_names, 'alpha_TR');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_TR');
M_.param_names_long = char(M_.param_names_long, 'alpha_TR');
M_.param_names = char(M_.param_names, 'gamma_TR');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_TR');
M_.param_names_long = char(M_.param_names_long, 'gamma_TR');
M_.param_names = char(M_.param_names, 'rho_g_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_g_i');
M_.param_names = char(M_.param_names, 'rho_g_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_g_c');
M_.param_names = char(M_.param_names, 'rho_TR');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_TR');
M_.param_names_long = char(M_.param_names_long, 'rho_TR');
M_.param_names = char(M_.param_names, 'tau_k_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_k\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_k_bar');
M_.param_names = char(M_.param_names, 'tau_n_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_n\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_n_bar');
M_.param_names = char(M_.param_names, 'tau_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_c_bar');
M_.param_names = char(M_.param_names, 'rho_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'rho_pCostar');
M_.param_names = char(M_.param_names, 'v_ss');
M_.param_names_tex = char(M_.param_names_tex, 'v\_ss');
M_.param_names_long = char(M_.param_names_long, 'v_ss');
M_.param_names = char(M_.param_names, 'kappa_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_o_ss');
M_.param_names = char(M_.param_names, 'kappa_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_r_ss');
M_.param_names = char(M_.param_names, 'u_ss');
M_.param_names_tex = char(M_.param_names_tex, 'u\_ss');
M_.param_names_long = char(M_.param_names_long, 'u_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'zeta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_ss');
M_.param_names_long = char(M_.param_names_long, 'zeta_ss');
M_.param_names = char(M_.param_names, 'yCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'yCo_ss');
M_.param_names = char(M_.param_names, 'o_revenue_ss');
M_.param_names_tex = char(M_.param_names_tex, 'o\_revenue\_ss');
M_.param_names_long = char(M_.param_names_long, 'o_revenue_ss');
M_.param_names = char(M_.param_names, 'Rstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rstar_ss');
M_.param_names = char(M_.param_names, 'y_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_star_ss');
M_.param_names = char(M_.param_names, 'sCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'sCo_ss');
M_.param_names = char(M_.param_names, 'sg_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sg\_ss');
M_.param_names_long = char(M_.param_names_long, 'sg_ss');
M_.param_names = char(M_.param_names, 'str_ss');
M_.param_names_tex = char(M_.param_names_tex, 'str\_ss');
M_.param_names_long = char(M_.param_names_long, 'str_ss');
M_.param_names = char(M_.param_names, 'T_ss');
M_.param_names_tex = char(M_.param_names_tex, 'T\_ss');
M_.param_names_long = char(M_.param_names_long, 'T_ss');
M_.param_names = char(M_.param_names, 'h_o_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_o\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_o_ss');
M_.param_names = char(M_.param_names, 'h_r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_r\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_r_ss');
M_.param_names = char(M_.param_names, 'p_ss');
M_.param_names_tex = char(M_.param_names_tex, 'p\_ss');
M_.param_names_long = char(M_.param_names_long, 'p_ss');
M_.param_names = char(M_.param_names, 'i_r');
M_.param_names_tex = char(M_.param_names_tex, 'i\_r');
M_.param_names_long = char(M_.param_names_long, 'i_r');
M_.param_names = char(M_.param_names, 'k_r');
M_.param_names_tex = char(M_.param_names_tex, 'k\_r');
M_.param_names_long = char(M_.param_names_long, 'k_r');
M_.param_names = char(M_.param_names, 'b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'b\_bar');
M_.param_names_long = char(M_.param_names_long, 'b_bar');
M_.param_names = char(M_.param_names, 'sf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sf\_ss');
M_.param_names_long = char(M_.param_names_long, 'sf_ss');
M_.param_names = char(M_.param_names, 'fb_star_bar');
M_.param_names_tex = char(M_.param_names_tex, 'fb\_star\_bar');
M_.param_names_long = char(M_.param_names_long, 'fb_star_bar');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'b_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_star_ss');
M_.param_names = char(M_.param_names, 'f_star_ss');
M_.param_names_tex = char(M_.param_names_tex, 'f\_star\_ss');
M_.param_names_long = char(M_.param_names_long, 'f_star_ss');
M_.param_names = char(M_.param_names, 'tb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tb\_ss');
M_.param_names_long = char(M_.param_names_long, 'tb_ss');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_names = char(M_.param_names, 'pCostar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pCostar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pCostar_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 81;
M_.param_nbr = 68;
M_.orig_endo_nbr = 81;
M_.aux_vars = [];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('SOE_simulations_pf_static');
erase_compiled_function('SOE_simulations_pf_dynamic');
M_.orig_eq_nbr = 81;
M_.eq_nbr = 81;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 23 104;
 0 24 0;
 1 25 0;
 0 26 0;
 2 27 105;
 3 28 0;
 0 29 0;
 0 30 0;
 4 31 0;
 0 32 0;
 0 33 0;
 5 34 0;
 0 35 0;
 0 36 0;
 6 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 7 41 0;
 8 42 0;
 0 43 106;
 0 44 0;
 0 45 107;
 9 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 10 57 0;
 11 58 0;
 0 59 0;
 0 60 0;
 12 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 13 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 14 86 0;
 15 87 0;
 16 88 0;
 17 89 108;
 18 90 0;
 19 91 0;
 20 92 0;
 0 93 0;
 0 94 0;
 0 95 109;
 0 96 0;
 0 97 0;
 0 98 110;
 0 99 0;
 21 100 0;
 0 101 0;
 22 102 0;
 0 103 0;]';
M_.nstatic = 54;
M_.nfwrd   = 5;
M_.npred   = 20;
M_.nboth   = 2;
M_.nsfwrd   = 7;
M_.nspred   = 22;
M_.ndynamic   = 27;
M_.equations_tags = {
  1 , 'name' , 'Capital Tax' ;
  2 , 'name' , 'Labor Tax' ;
  3 , 'name' , 'Consumption Tax' ;
  4 , 'name' , 'Government Consumtpion' ;
  5 , 'name' , 'Government Investment' ;
  6 , 'name' , 'Transfers' ;
  7 , 'name' , 'Oil Revenue' ;
  8 , 'name' , 'Optimizer Marginal Utility of Consumption' ;
  9 , 'name' , 'Rule of Thumb Marginal Utility of Consumption' ;
  10 , 'name' , 'Aggregate Private Consumption' ;
  11 , 'name' , 'Optimizer Consumption/Leisure Condition' ;
  12 , 'name' , 'Rule of Thumb Comsumption/Leausre Condition' ;
  13 , 'name' , 'Aggregate Labor Supply' ;
  14 , 'name' , 'Domestic Interest Rate' ;
  15 , 'name' , 'Optimizer Euler Equation' ;
  16 , 'name' , 'Final Good Production' ;
  17 , 'name' , 'Domestic Demand for Foreign Goods' ;
  18 , 'name' , 'Doemstic Demand for Home Goods' ;
  19 , 'name' , 'Foreign Demand for Home Goods' ;
  20 , 'name' , 'Home Good Production Function' ;
  21 , 'name' , 'Home Good Market Clearing' ;
  22 , 'name' , 'Final Good Market Clearing' ;
  23 , 'name' , 'GDP In Terms of Foreing Good' ;
  24 , 'name' , 'Trade Balance' ;
  25 , 'name' , 'Aggregate Privately Held Foreign Debt' ;
  26 , 'name' , 'Balance of Payments Identity' ;
  27 , 'name' , 'Country Premium' ;
  28 , 'name' , 'Evolution of Optimizer Capital' ;
  29 , 'name' , 'Aggregate Private Capital' ;
  30 , 'name' , 'Aggregate Private Investment' ;
  31 , 'name' , 'Tobins q for Private Investment' ;
  32 , 'name' , 'Return to Capital Equals Marginal Product of Capital' ;
  33 , 'name' , 'Wage Equals Marginal Product of Labor' ;
  34 , 'name' , 'Optimzer Investment First Order Condition' ;
  35 , 'name' , 'Import Market Clearing' ;
  36 , 'name' , 'Optimizer Consumption Composite' ;
  37 , 'name' , 'Rule of Thumb Consumption Composite' ;
  38 , 'name' , 'Optimizer Wealth Effect on Labor Supply 1' ;
  39 , 'name' , 'Optimizer Wealth Effect on Labor Supply 2' ;
  40 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 1' ;
  41 , 'name' , 'Rule of Thumb Wealth Effect on Labor Supply 2' ;
  42 , 'name' , 'Government Budget Constraint' ;
  43 , 'name' , 'Transfers to Optimizers' ;
  44 , 'name' , 'Transfers to Rule of Thumb' ;
  45 , 'name' , 'Profits of Home Good Producer' ;
  46 , 'name' , 'Evolution of Government Capital' ;
  47 , 'name' , 'Rule of Thumb Budget Constraint' ;
  48 , 'name' , 'Real GDP' ;
  49 , 'name' , 'Annual Aggregate Debt to GDP' ;
  50 , 'name' , 'Aggregate Capitak' ;
  51 , 'name' , 'Tax Revenue' ;
  52 , 'name' , 'Revenue' ;
  53 , 'name' , 'Spending' ;
  54 , 'name' , 'Annual Government Debt to GDP' ;
  55 , 'name' , 'Annual Private Debt to GDP' ;
  56 , 'name' , 'Government Consumption to GDP' ;
  57 , 'name' , 'Government Investment to GDP' ;
  58 , 'name' , 'Transfers to GDP' ;
  59 , 'name' , 'Tax Revenue to GDP' ;
  60 , 'name' , 'Oil Revenue to GDP' ;
  61 , 'name' , 'Revenue to GDP' ;
  62 , 'name' , 'Spending to GDP' ;
  63 , 'name' , 'Primary Balance to GDP' ;
  64 , 'name' , 'Interest Payments to GDP' ;
  65 , 'name' , 'Annual Net Country Premium ' ;
  66 , 'name' , 'Real Wage' ;
  67 , 'name' , 'Real Non-Oil GDP' ;
  68 , 'name' , 'Consumption Tax Revenue to GDP' ;
  69 , 'name' , 'Labor Tax Revenue to GDP' ;
  70 , 'name' , 'Capital Tax Revenue to GDP' ;
  71 , 'name' , 'Time Preference Shifter Process' ;
  72 , 'name' , 'Optimizer Labor Supply Preference Shifter Process' ;
  73 , 'name' , 'Rule of Thumb Labor Supply Preference Shifter Process' ;
  74 , 'name' , 'Investment Specific Productivity Process' ;
  75 , 'name' , 'TFP Process' ;
  76 , 'name' , 'Growth Rate Process' ;
  77 , 'name' , 'Idiosyncratic Component of Country Premium Process' ;
  78 , 'name' , 'Foreign Inerest Rate Process' ;
  79 , 'name' , 'Foreign GDP Process' ;
  80 , 'name' , 'Change in Government Debt Over GDP' ;
  81 , 'name' , 'Trade Balance Over GDP' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(81, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(68, 1);
M_.NNZDerivatives = [353; 817; -1];
close all;
M_.params( 3 ) = 1.000000001;
sigma = M_.params( 3 );
M_.params( 6 ) = 0.015;
delta = M_.params( 6 );
M_.params( 8 ) = 0.27;
o = M_.params( 8 );
M_.params( 9 ) = 0.74;
chi = M_.params( 9 );
M_.params( 13 ) = .7;
omega = M_.params( 13 );
M_.params( 19 ) = 1;
omega_G = M_.params( 19 );
M_.params( 20 ) = 0.015;
delta_g = M_.params( 20 );
M_.params( 12 ) = .25;
o_c = M_.params( 12 );
M_.params( 21 ) = .1;
o_kg = M_.params( 21 );
M_.params( 15 ) = M_.params(21)*.34;
gamma = M_.params( 15 );
M_.params( 5 ) = 0.34-M_.params(15);
alpha = M_.params( 5 );
M_.params( 14 ) = 0.25;
eta_star = M_.params( 14 );
M_.params( 61 ) = .256;
sf_ss = M_.params( 61 );
M_.params( 52 ) = 0.106;
sg_ss = M_.params( 52 );
M_.params( 53 ) = .049;
str_ss = M_.params( 53 );
M_.params( 51 ) = 0.082;
sCo_ss = M_.params( 51 );
M_.params( 45 ) = 1.004962931573204;
a_ss = M_.params( 45 );
M_.params( 49 ) = 1.000978953692953;
Rstar_ss = M_.params( 49 );
M_.params( 18 ) = 1.012705786773885;
xi_bar = M_.params( 18 );
M_.params( 38 ) = .12;
tau_c_bar = M_.params( 38 );
M_.params( 36 ) = .25;
tau_k_bar = M_.params( 36 );
M_.params( 37 ) = .04;
tau_n_bar = M_.params( 37 );
M_.params( 60 ) = 1.42;
b_bar = M_.params( 60 );
M_.params( 58 ) = .16;
i_r = M_.params( 58 );
M_.params( 55 ) = 0.29543;
h_o_ss = M_.params( 55 );
M_.params( 56 ) = 0.29543;
h_r_ss = M_.params( 56 );
M_.params( 40 ) = 1;
v_ss = M_.params( 40 );
M_.params( 43 ) = 1;
u_ss = M_.params( 43 );
M_.params( 57 ) = 1;
p_ss = M_.params( 57 );
M_.params( 44 ) = 1;
z_ss = M_.params( 44 );
M_.params( 46 ) = 1;
zeta_ss = M_.params( 46 );
M_.params( 50 ) = 1;
y_star_ss = M_.params( 50 );
M_.params( 68 ) = 1;
pCostar_ss = M_.params( 68 );
M_.params( 23 ) = 1;
mu = M_.params( 23 );
M_.params( 4 ) = 3.421587887494021;
phi = M_.params( 4 );
M_.params( 1 ) = 0.738370963191099;
varsigma = M_.params( 1 );
M_.params( 2 ) = 2.210565902756527;
hpsi = M_.params( 2 );
M_.params( 7 ) = 6.075943008381720;
eta = M_.params( 7 );
M_.params( 16 ) = 8.854549591310821;
gamma_k = M_.params( 16 );
M_.params( 11 ) = 0.794029592118338;
eta_c = M_.params( 11 );
M_.params( 10 ) = 0.700769221922841;
upsilon = M_.params( 10 );
M_.params( 33 ) = 0.773151296679890;
rho_g_i = M_.params( 33 );
M_.params( 27 ) = 2.581136188194960;
alpha_g_i = M_.params( 27 );
M_.params( 28 ) = (-1.820671564944772);
gamma_g_i = M_.params( 28 );
M_.params( 34 ) = 0.881944929959026;
rho_g_c = M_.params( 34 );
M_.params( 29 ) = 0.593524641111012;
alpha_g_c = M_.params( 29 );
M_.params( 30 ) = (-0.497803637718900);
gamma_g_c = M_.params( 30 );
M_.params( 35 ) = 0.473017824489847;
rho_TR = M_.params( 35 );
M_.params( 31 ) = 5.462229514950716;
alpha_TR = M_.params( 31 );
M_.params( 32 ) = (-0.261494559041695);
gamma_TR = M_.params( 32 );
M_.params( 39 ) = 0.87142;
rho_pCostar = M_.params( 39 );
save('SOE_simulations_pf_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('SOE_simulations_pf_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
